const categories=[
  {name:"全部故事",count:1284,code:"ALL"},{name:"悬疑迷局",count:326,code:"SUS"},{name:"都市情感",count:284,code:"ROM"},{name:"家庭真相",count:217,code:"FAM"},{name:"奇闻异事",count:193,code:"ODD"},{name:"科幻未来",count:146,code:"SCI"},{name:"治愈短篇",count:118,code:"LIT"}
];

const stories=[
  {slug:"red-shoes",title:"凌晨三点，门外又响起了敲门声",category:"悬疑迷局",chapter:"第 8 章",glyph:"⌑",tone:"rust",summary:"那双红色高跟鞋再次出现，而这一次，鞋尖正对着我的门。",tags:["公寓","反转","连载"],date:"2026-07-19",dateLabel:"昨日更新",reads:86400,readsLabel:"8.6万",content:["第三次敲门声落下时，我没有动。手机屏幕停在监控画面上，走廊空无一人，只有那双红色高跟鞋安静地摆在门垫中央。","我把声音调到最大。电流杂音里，有人贴着摄像头低声数数：七、六、五……那是我母亲的声音。她已经去世十二年了。","门把手缓缓转动。我这才想起，搬进来第一天，房东给过我两把钥匙。其中一把，此刻正从门缝下被人轻轻推了进来。钥匙上缠着一张褪色的住院腕带，名字是我的，日期却是明天。","我后退一步，撞翻了玄关的纸箱。箱底露出一张旧报纸：十二年前，本楼七层发生火灾，唯一失踪的女孩穿着红色高跟鞋。照片上的女孩不是别人——正是我每天在镜子里看到的脸。"]},
  {slug:"empty-seat",title:"婚礼上，父亲身边的空位",category:"家庭真相",chapter:"完结篇",glyph:"Ⅱ",tone:"gold",summary:"婚礼开始前，父亲坚持为一个不存在的人留了座位。",tags:["亲情","婚礼","催泪"],date:"2026-07-18",dateLabel:"2 天前",reads:72100,readsLabel:"7.2万",content:["司仪第三次问起那个空位时，父亲只是把椅子擦得更干净。他说，等一个迟到了二十六年的人。","仪式开始，酒店门被推开。进来的女人与我有一双一模一样的眼睛，手里捧着我婴儿时期丢失的银锁。","父亲终于告诉我，那不是客人，而是把我带到这个世界上的人。二十六年前，她为了让我能活下来，签下了放弃治疗的同意书。","那张空椅子从来不是留给亡者。它留给的是一个父亲不敢忘记、却也不敢在女儿最幸福的日子里说出口的真相。"]},
  {slug:"last-message",title:"前任去世后，我收到他的第 37 条短信",category:"都市情感",chapter:"第 5 章",glyph:"37",tone:"blue",summary:"号码早已注销，但每逢周五，短信仍会准时到达。",tags:["旧爱","短信","秘密"],date:"2026-07-20",dateLabel:"刚刚更新",reads:69800,readsLabel:"6.9万",content:["第 37 条短信只有一句：别去我们第一次见面的咖啡馆。我盯着时间——周五，下午四点零七分，和前面三十六条一模一样。","我还是去了。店已经关门，玻璃上贴着招租告示，里面却亮着一盏属于我们旧座位的灯。","桌上放着一部黑色手机。屏幕里存着三十七封定时邮件，最后一封的收件人不是我，而是一个我从未听过的名字。","身后的门铃突然响了。一个小女孩站在雨里，抬头问我：你就是爸爸每年都会写信的那位阿姨吗？"]},
  {slug:"elevator-thirteen",title:"电梯里不存在的第十三层",category:"奇闻异事",chapter:"第 3 章",glyph:"13",tone:"violet",summary:"按钮只有十二层，可午夜后，显示屏总会多出一个数字。",tags:["电梯","午夜","规则"],date:"2026-07-16",dateLabel:"4 天前",reads:57300,readsLabel:"5.7万",content:["物业说这栋楼从来没有十三层。可那晚十二点后，电梯没有停在我按下的九楼，而是继续上升。","显示屏跳出鲜红的 13。门开后，走廊和我家那层一模一样，只是每扇门上都贴着明天的日期。","1306 的门虚掩着。我从门缝看见自己坐在餐桌边，正在给现在的我写一张纸条：无论听到谁叫你的名字，都别回头。","就在这时，身后的电梯门关上了。黑暗里，一个和我声音完全相同的人轻轻说：你终于回来了。"]},
  {slug:"memory-shop",title:"我在旧货市场买到一段陌生记忆",category:"科幻未来",chapter:"第 12 章",glyph:"∞",tone:"teal",summary:"售价二十元的芯片里，藏着一场尚未发生的告别。",tags:["记忆","未来","循环"],date:"2026-07-17",dateLabel:"3 天前",reads:49200,readsLabel:"4.9万",content:["摊主说那是一枚坏掉的音乐芯片。我把它接入旧播放器，听见的却是自己的哭声。","记忆里，我站在一座被海水淹没的城市，和一个看不清脸的人告别。远处钟楼显示的年份，是三年后。","芯片末尾有一串坐标。我找到那里时，只看见一间尚未开业的记忆商店，橱窗海报上印着我的照片。","店主从暗处走出来，把二十元放回我手里：这段记忆不是你买走的，是三年后的你寄回来，拜托我今天交给你的。"]},
  {slug:"window-light",title:"对面那盏永远为我亮着的灯",category:"治愈短篇",chapter:"短篇",glyph:"✦",tone:"cream",summary:"失眠的第 100 天，我终于敲响了对面那扇门。",tags:["失眠","陌生人","温暖"],date:"2026-07-15",dateLabel:"5 天前",reads:44600,readsLabel:"4.4万",content:["搬来后，我每晚都看见对面窗台亮着一盏橘色小灯。它从不熄灭，像在陪我熬过每一个睡不着的夜。","第一百天，我带着一袋橘子去敲门。开门的是位白发老人，他身后并没有灯，只有一面镜子。","老人笑着指向我的窗户：孩子，亮着灯的一直是你家。我只是每天坐在这里，让你知道世界上还有人醒着。","那晚我第一次关掉灯。清晨醒来时，门把手上挂着一张纸条：以后想说话，就来敲门。"]},
  {slug:"roommate",title:"合租室友从来不在镜子里出现",category:"悬疑迷局",chapter:"第 6 章",glyph:"◐",tone:"ink",summary:"直到我翻到入住合同，才发现签名栏一直只有我。",tags:["合租","镜子","身份"],date:"2026-07-14",dateLabel:"6 天前",reads:39800,readsLabel:"3.9万",content:["林夏搬进来两个月，我从未在镜子里见过她。起初我以为只是角度，直到她站在我身后替我梳头。","镜子里只有一把悬在空中的木梳。我猛地回头，她却像往常一样问我晚饭吃什么。","我冲去中介翻合同。纸上只有我的签名，紧急联系人一栏却写着林夏的电话。拨过去后，接电话的是我自己。","电话里的声音说：千万别让她知道你已经想起来了。三年前死在这间房里的人，根本不是林夏。"]},
  {slug:"rainy-platform",title:"雨夜末班车，没有终点站",category:"奇闻异事",chapter:"第 4 章",glyph:"↟",tone:"green",summary:"车票背面写着一条规则：途中无论看见谁，都不要下车。",tags:["末班车","规则","归途"],date:"2026-07-13",dateLabel:"一周前",reads:35200,readsLabel:"3.5万",content:["末班车开出十分钟后，我发现车窗外还是同一个站台。雨里站着的人越来越多，他们都没有撑伞。","售票员递给我一张没有终点的车票，背面写着：不要回应敲窗的人，尤其当那个人是你自己。","第三圈，我看见十九岁的自己站在雨里。他抱着那只早就走丢的狗，拼命朝我挥手。","车门打开了一条缝。售票员低声问我：你要回到过去，还是带着遗憾回家？"]}
];

const infoPages={
  about:{title:"关于续页",intro:"续页是一座为移动端阅读设计的原创故事档案馆。",sections:[["我们在做什么","我们把散落在信息流里的连载故事整理成清晰、可搜索、可直接分享的独立档案。每篇故事都有固定链接，读者无需注册即可阅读。"],["内容原则","所有故事应获得合法发布授权，并清楚区分原创、授权转载与广告内容。我们不发布仇恨、欺诈、露骨成人内容或侵犯他人版权的作品。"],["更新节奏","故事库计划每周更新三次。具体时间会显示在首页与每篇档案的更新信息中。"]]},
  privacy:{title:"隐私政策",intro:"最后更新：2026 年 7 月 20 日",sections:[["我们收集的信息","当前静态演示站不保存订阅邮箱，也没有账号系统。正式启用数据服务后，本政策会同步更新。"],["Cookie 与广告","为了保存阅读偏好、统计访问效果并展示相关广告，未来可能使用 Cookie 或类似技术。第三方广告服务商也可能按其隐私政策处理设备与访问数据。"],["你的选择","你可以在浏览器中限制 Cookie、取消订阅，或联系我们申请访问、更正或删除相关信息。"],["数据安全","我们采用合理措施保护数据，但互联网传输无法保证绝对安全。"]]},
  terms:{title:"使用条款",intro:"访问续页即表示你同意遵守以下基本规则。",sections:[["内容版权","除非另有标注，本站排版、品牌元素与原创故事受版权保护。未经授权，不得批量复制、镜像、改编或用于商业分发。"],["合理使用","你可以分享本站公开页面链接，也可以在法律允许的范围内引用少量内容并注明出处。"],["广告与外部链接","广告会以明确标识与正文区分。外部网站由其运营方负责。"],["免责声明","故事内容仅供文学阅读。我们会努力保持页面准确可用，但不保证服务永不中断。"]]},
  contact:{title:"联系与广告合作",intro:"欢迎原创投稿、版权合作与品牌广告咨询。",sections:[["广告合作","首页、故事正文与侧栏均预留标准广告位。正式投放前会确认素材规格、展示周期、跳转目标与内容合规要求。"],["内容合作","投稿请附作品简介、完整样稿、版权声明与可联系邮箱。请勿提交未经授权的转载内容。"],["联系我们","当前演示站尚未绑定正式业务邮箱。上线前请将此处替换为你的品牌邮箱。"]]}
};

function storyCard(story,index){return `<article class="story-card"><div class="cover tone-${story.tone}"><span>${String(index+1).padStart(2,"0")}</span><span class="category">${story.category}</span><div class="glyph">${story.glyph}</div><span class="chapter">${story.chapter}</span></div><div class="card-body"><div class="card-meta"><span>${story.dateLabel}</span><span>${story.readsLabel} 阅读</span></div><h3><a href="story.html?slug=${story.slug}">${story.title}</a></h3><p>${story.summary}</p><div class="tags">${story.tags.slice(0,2).map(tag=>`<span>#${tag}</span>`).join("")}</div><a class="read-link" href="story.html?slug=${story.slug}"><span>打开档案</span><b>→</b></a></div></article>`}

function initHome(){
  let active="全部故事",query="",sort="popular";
  const folderList=document.querySelector("#folder-list"),grid=document.querySelector("#story-grid"),count=document.querySelector("#result-count"),title=document.querySelector("#active-title"),empty=document.querySelector("#empty-state");
  function renderFolders(){folderList.innerHTML=categories.map(c=>`<button class="folder ${c.name===active?"active":""}" data-category="${c.name}"><span class="folder-icon"></span><span><b>${c.name}</b><small>${c.count} 篇</small></span><i>${c.code}</i></button>`).join("");folderList.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{active=button.dataset.category;render()}))}
  function render(){let items=stories.filter(s=>(active==="全部故事"||s.category===active)&&[s.title,s.summary,s.category,...s.tags].join(" ").toLowerCase().includes(query.toLowerCase()));items.sort((a,b)=>sort==="newest"?b.date.localeCompare(a.date):b.reads-a.reads);title.textContent=active;count.textContent=`${items.length} 份匹配档案`;grid.innerHTML=items.map(storyCard).join("");empty.hidden=items.length!==0;renderFolders()}
  document.querySelector("#story-search").addEventListener("input",event=>{query=event.target.value.trim();render()});document.querySelector("#search-form").addEventListener("submit",event=>{event.preventDefault();document.querySelector("#library").scrollIntoView({behavior:"smooth"})});document.querySelector("#sort-select").addEventListener("change",event=>{sort=event.target.value;render()});document.querySelector("#newsletter-form").addEventListener("submit",event=>{event.preventDefault();document.querySelector("#newsletter-note").textContent="这是免费演示站，当前不会保存你的邮箱。"});render();
}

function initStory(){
  const slug=new URLSearchParams(location.search).get("slug")||"red-shoes",story=stories.find(s=>s.slug===slug)||stories[0];document.title=`${story.title}｜续页故事库`;
  document.querySelector("#reader").innerHTML=`<article class="reader-main"><nav class="breadcrumb"><a href="./">故事库</a><span>/</span><span>${story.category}</span><span>/</span><b>${story.chapter}</b></nav><header class="article-head"><div class="article-label"><span>档案已开启</span><i>FILE / ${story.slug.toUpperCase()}</i></div><h1>${story.title}</h1><p>${story.summary}</p><div class="article-stats"><span>更新于 ${story.date}</span><span>${story.readsLabel} 次阅读</span><span>预计阅读 4 分钟</span></div></header><div class="ad-slot reader-ad"><span>ADVERTISEMENT</span><p>广告展示位 · 728 × 90</p></div><div class="prose"><p class="dropcap">${story.content[0]}</p>${story.content.slice(1,3).map(p=>`<p>${p}</p>`).join("")}<div class="ad-slot mid-ad"><span>ADVERTISEMENT</span><p>文章内广告位 · 自适应</p></div>${story.content.slice(3).map(p=>`<p>${p}</p>`).join("")}</div><div class="chapter-end"><span>TO BE CONTINUED</span><h2>本章完</h2><p>下一章正在整理入库。收藏本页，或回到故事库发现更多故事。</p><a href="./">返回故事库</a></div></article><aside class="reader-side"><div class="reading-card"><span>当前档案</span><strong>${story.chapter}</strong><p>${story.category}</p></div><div class="ad-slot tall-ad"><span>ADVERTISEMENT</span><p>广告展示位<br>300 × 600</p></div></aside>`;
}

function initInfo(){const key=new URLSearchParams(location.search).get("page")||"about",page=infoPages[key]||infoPages.about;document.title=`${page.title}｜续页故事库`;document.querySelector("#info-content").innerHTML=`<div class="section-label">PUBLIC DOCUMENT</div><h1>${page.title}</h1><p class="intro">${page.intro}</p>${page.sections.map(([title,text])=>`<section><h2>${title}</h2><p>${text}</p></section>`).join("")}`}

const page=document.body.dataset.page;if(page==="home")initHome();if(page==="story")initStory();if(page==="info")initInfo();
