window.STORY_ARCHIVE = [
  {
    slug: "the-broken-home",
    fileNo: "A-001",
    title: { en: "The Broken Home", zh: "家宴上的囚徒" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "Hours after losing her twins, Eva is dragged to a family banquet and forced to sign away her marriage—until she reveals the documents that can bring the entire dynasty down.",
      zh: "刚失去龙凤胎的伊芙被拖到家宴上逼迫离婚，直到她拿出足以让整个家族崩塌的文件。"
    },
    warning: {
      en: "Fiction. Contains pregnancy loss, coercion and family abuse.",
      zh: "虚构故事。包含流产、胁迫与家庭虐待情节。"
    },
    tone: "rust",
    glyph: "BH",
    content: {
      en: [
        "## Chapter One: The Banquet",
        "“Swallow the divorce papers along with the babies you lost in the operating room. A useless woman who cannot produce an heir has no place at our family’s table.”",
        "At the center of a lavish banquet attended by more than a hundred members of the dynasty, Eva’s mother-in-law hurled a stamped hospital settlement report into her face. Eva had been dragged from the hospital only hours earlier, her skin white as paper.",
        "“Mom… I lost my twins on the operating table this morning. You brought your son’s mistress here and now you are forcing me to die in front of the whole family?” Eva collapsed to the floor, clutching her abdomen as blood slowly stained her loose hospital clothes.",
        "The husband she had loved for seven years did not even look up. With one arm around his pregnant mistress, Thomas calmly cut his steak. “If my mother tells you to sign, then sign. You could not even keep a child alive. Stop dirtying our carpet, take the divorce, and crawl back to the slum you came from.”",
        "His mother stepped forward and ground the heel of her shoe into Eva’s fingers. Around the table, relatives and executives who had always pretended to be kind watched without lifting a hand. A few even laughed.",
        "“This is your last day here,” the older woman said. “Guards, throw her into the rain with the rest of the trash.”",
        "Eva did not scream. With her swollen hand, she pulled three stamped bank demand notices and a receipt from the tax authority out of her bag. Then she looked at Thomas and smiled without warmth.",
        "“You seem to have forgotten that the mansion, the Rolls-Royce and every guarantee behind your company’s listing are in my name. I signed away my children in an operating room this morning, and now you want me to sign away my marriage at this table. Fine. We can all go to hell together.”",
        "## Chapter Two: The Only Card Left",
        "The room went silent. Thomas’s silver knife struck the floor. As if remembering something terrifying, he lunged for the papers and read the official stamps. His face drained of color and his knees gave way.",
        "“No. This cannot be real. When did you revoke the guarantees? And this tax audit…”",
        "His mother still did not understand. “Why are you afraid of her? The company is listed. We are rich now.”",
        "“Be quiet!” Thomas screamed. “Every bridge loan for the listing was secured against this house and my shares. The house is in Eva’s name. Every primary loan and personal guarantee depends on her credit.”",
        "Holding the edge of the table, Eva rose inch by inch. It hurt, but she stood with more dignity than anyone else in the room.",
        "“You moved marital assets, cheated on me, and even stopped my prenatal examinations to please your mistress’s family. Did you truly think I knew nothing? I stayed silent because I wanted to protect my children. When their hearts stopped this morning, the last mercy I had for you stopped with them.”",
        "## Chapter Three: Nothing Left",
        "Eva put her phone on speaker. The chief legal officer of the city’s largest commercial bank answered.",
        "“Ms. Eva, following the divorce petition and evidence of malicious transfer of marital property that you submitted one hour ago, we have applied for pretrial asset preservation. Because you withdrew your joint personal guarantee, the company’s credit facility was automatically suspended five minutes ago.”",
        "Phones began chiming around the room. The notices all said the same thing: the controlling shareholder was suspected of fraud and serious marital misconduct; company accounts were frozen, the listing was halted, and liquidation proceedings were beginning.",
        "The relatives and executives who had mocked Eva suddenly turned on Thomas. Their own money was trapped. “You have ruined us!” one shouted. “Why did you provoke her?” cried another.",
        "Thomas crawled across the floor. “Eva, I was wrong. My mother forced me. I will kneel, I will clean your shoes—just restore the guarantee.” He reached for the hand his mother had crushed under her heel.",
        "The pregnant mistress saw her dream collapse and tried to slip away without even collecting her bags.",
        "Eva never looked back. Wrapped in a thin hospital gown and accompanied by police officers and her lawyers, she walked out of the mansion that had held seven years of her pain.",
        "Half an hour later, the court sealed the front gate. Thomas’s mother collapsed under the weight of the debt. Thomas lost the company, the house and every privilege he had taken for granted. Millions in personal liabilities would follow him for the rest of his life.",
        "— End —"
      ],
      zh: [
        "## 第一章：家宴上的囚徒",
        "“把你那刚在手术室里夭折的死胎和离婚协议书一起吞下去，你这个生不出继承人的废物，不配上我们家的百亿家宴大桌！”",
        "在上百名豪门核心成员齐聚的奢华家宴正中央，恶毒婆婆将一份盖着红印的医院清算报告单砸在刚被强行从医院拽出来、脸白得像纸的儿媳伊芙脸上。",
        "“妈……我今天早上刚在手术台上失去了龙凤胎。你为了给这个小三转正，竟然当着全家族的面逼我去死？”伊芙瘫坐在地上，捂着剧痛的腹部，宽大的病服下隐隐透出猩红。",
        "她爱了七年的丈夫托马斯却搂着怀孕的小三，连头都不抬：“我妈让你签你就签。连孩子都保不住，别弄脏这里的地毯。签了字，滚回你的贫民窟。”",
        "婆婆踩住伊芙抓着协议书的手指。周围平日和蔼的亲戚和集团高管无人阻拦，甚至有人发出刺耳的笑声。",
        "“今天就是你的死期。保镖，把她像垃圾一样扔进外面的暴雨里！”",
        "伊芙没有哭喊。她用被踩得红肿的手，从怀里掏出三份盖章的银行催缴通知书和一份税务局实名举报回执，冰冷地看着丈夫和婆婆。",
        "“托马斯，你忘了这栋豪宅、劳斯莱斯，还有你公司上市的所有担保人，写的都是我的名字。我刚在手术室失去孩子，你们就在桌上逼我离婚。那我们现在就一起下地狱吧。”",
        "## 第二章：底层的底牌",
        "全场死寂。托马斯手里的银餐刀掉在地上。他像突然想起了极其恐怖的事，一把夺过单据。看清官方红章后，他整个人瘫软在地。",
        "“不……这不可能！你什么时候撤销了担保？还有这个税务审计……”",
        "婆婆还在破口大骂：“儿子，你怕这个扫把星干什么？公司都上市了，我们现在是有钱人！”",
        "“妈，你闭嘴！”托马斯绝望地咆哮，“公司上市的所有过桥资金，全用这栋房子和我的股份抵押。而房子写的是伊芙的名字，所有主贷人和信用担保都靠她的个人信用！”",
        "伊芙扶着桌角，一寸一寸、极其艰难却无比尊严地站起来。",
        "“你转移资产、婚内出轨，甚至为了迎合小三的家庭停掉我的产检。你真以为我什么都不知道？我隐忍，是因为想保住孩子。今天早上孩子彻底没了心跳时，我对你最后一点仁慈也死了。”",
        "## 第三章：一无所有",
        "伊芙拿出手机，当着全场亲戚和高管按下免提。电话那头是本地最大商业银行的首席法务代表。",
        "“伊芙女士，根据您一小时前提交的离婚诉讼及婚内财产恶意转移证明，我们已向法院申请诉前财产保全。由于您撤销了对托马斯先生公司的个人连带担保，公司的信用额度已在五分钟前自动熔断。”",
        "全场手机疯狂响起：大股东涉嫌欺诈，公司账户被冻结，上市程序中止，并将进入全面清算。",
        "原本冷眼旁观的亲戚和高管利益受损，瞬间变脸，冲着丈夫和婆婆大骂：“托马斯，你害死我们了！”“你惹她干什么？”",
        "托马斯像狗一样爬过来：“老婆，我错了，是我妈逼我的！我跪下给你擦鞋，你把担保拿回来！”他伸手去抓伊芙那只被踩得红肿的手。",
        "怀孕的小三知道豪门梦碎了，连行李都来不及拿，低着头想往外逃。",
        "伊芙没有再看他们。她裹紧单薄的医院病服，在警察和律师陪同下，一步一步走出这栋装满她血泪的伪豪门别墅。",
        "半小时后，法院封条贴上别墅大门。婆婆承受不住巨债，当场中风；托马斯不仅一无所有，还将背负数千万个人债务。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "cleaning-house",
    fileNo: "A-003",
    title: { en: "Cleaning House", zh: "清理门户" },
    category: { en: "Justice & Reckoning", zh: "正义审判" },
    summary: {
      en: "An orphan treated as living trash waits three years to reveal the ledger that proves who stole his inheritance—and who destroyed his father.",
      zh: "一个被当作垃圾对待的孤儿隐忍三年，终于拿出证明遗产被盗和父亲被害的完整账目。"
    },
    warning: {
      en: "Fiction. Contains child abuse, coercion and threats.",
      zh: "虚构故事。包含虐待未成年人、胁迫与威胁情节。"
    },
    tone: "gold",
    glyph: "CH",
    content: {
      en: [
        "I was on my knees beneath the dining table while my uncle’s polished shoe pressed down on my knuckles.",
        "Above me, his family of three drank the wine my father had loved. Tonight it was their victory bottle, opened to celebrate removing me from my own inheritance.",
        "“Call me Dad,” my uncle said, lifting my chin with the toe of his shoe as if teasing an injured dog. “Do that and I might give you the bloody piece of steak in my bowl. Your dead father could never have fed you meat this fine.”",
        "I stared back without tears. Since the court placed me in their care, I had become the mansion’s living garbage. My aunt cut her food with perfect elegance and never once looked at me, as though I were a patch of mold in the air.",
        "“When your mother ran away, leaving you with us was her way of disposing of waste,” she said. “And those assets your father left? Think of them as interest we collected from him.”",
        "At last I ran into the rain. I collapsed at an intersection, and the police returned me to their house like an unwanted parcel. When the door closed, my uncle did not strike me. He opened a drawer, removed a camera and pushed me toward the dark basement where he planned to ‘train’ me.",
        "He wanted a recording of me begging and behaving irrationally. With it, he could manufacture a diagnosis of severe mental illness and erase my inheritance claim forever.",
        "Before he could aim the camera, the study door crashed open. The company’s former finance director—the old man they believed had long since disappeared—entered with two solemn lawyers. He ignored my uncle, placed his jacket over my scarred shoulders and faced me.",
        "“Young master, every account now balances,” he said, his voice shaking while his eyes remained hard. “From your grandfather’s generation to the conspiracy that drove your father to his death, every movement of money is documented in this encrypted archive.”",
        "I stood, walked to the camera and pressed Delete. Then I turned toward the couple whose faces had gone gray.",
        "“Which one of us did you call waste?”",
        "For three years I had moved like a ghost through the currents of capital, slowly draining the system they used against me. I never needed violence. I simply returned every injury they had inflicted, enlarged by the weight of evidence and law.",
        "When the final liquidation agreement struck my uncle’s face, court seals went onto the villa that had once imprisoned me. I watched him sign like a creature with nowhere left to crawl. His proud wife knelt in the rain and begged me to leave them a few coins.",
        "I entered the car and started the engine. In the mirror, they looked like two bodies forgotten by the world, stranded in the middle of an empty street.",
        "Dignity does not need to be argued for. Once you become the author of the rules, everyone who stood on your head eventually begs you to move your foot.",
        "— End —"
      ],
      zh: [
        "我跪在餐桌底下，姑父那双擦得锃亮的皮鞋正踩在我指关节上。",
        "餐桌上，他们一家三口正在享用红酒。那是父亲生前最爱的一款，如今却成了姑父庆祝把我踢出遗产继承权的庆功酒。",
        "“儿子，叫一声爸。”姑父用脚尖挑起我的下巴，语气温柔得像逗一只残疾的狗，“叫我爸，我就把碗里那块带血的牛排赏给你。毕竟你那死鬼老爹，可没本事让你吃上这么好的肉。”",
        "我盯着他，瞳孔里没有泪，只有一汪死水。自从被判给他们，我就成了这栋豪宅里的活体垃圾。姑姑坐在对面优雅地切着食物，仿佛我是空气中一道令人作呕的霉味。",
        "“你妈跑的时候把你留给我，就是在处理垃圾。你以为你爸留下的资产是你的？那是我们当年从他手里抠出来的利息。”",
        "我忍到极致，跑进雨里，晕倒在路口，又被警察送回他们家。门关上的一刻，姑父没有打我。他从抽屉里拿出摄像机，把我推进阴暗的地下室——那是他准备对我进行驯化的地方。",
        "他要录下我跪地求饶、像疯子一样表演的视频，再伪造一份我患有严重精神疾病的诊断书，彻底抹除我的继承权。",
        "就在镜头即将对准我时，书房门被撞开。公司曾经的老财务总监带着两名律师闯进来。他没有看姑父，直接走到我面前，用西装外套盖住我满是伤痕的肩膀。",
        "“少爷，账目全部对齐了。”老人声音发抖，眼神却冷得像刀，“从你爷爷那一代，到你父亲被他们合谋逼死，所有资金流转证据都在这个加密文件夹里。”",
        "我站起来，走到摄像机前按下删除键，再看向那对曾经高高在上、如今面如死灰的夫妻。",
        "“你们刚才说，谁是垃圾？”",
        "蛰伏三年，我像幽灵一样在资本暗流里一点点抽干他们的血。我没有杀他们，只是把他们施加给我的一切按比例放大，原封不动地返还。",
        "最后一份资产清算协议拍在姑父脸上时，囚禁过我的别墅被贴上法院封条。我看着他在协议上签字，看着他傲慢的妻子跪在雨里求我留下一分钱。",
        "我坐进车里发动引擎。倒车镜里，他们像两具被世界遗忘的尸体，站在空荡荡的街道中央。",
        "尊严不需要争。当你成了规则的制定者，所有踩在你头上的人，最后都会求你把脚挪开。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "judgment-from-a-wheelchair",
    fileNo: "A-004",
    title: { en: "Judgment from a Wheelchair", zh: "轮椅上的审判" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "A disabled heir watches his father and wife plan to steal his mother’s estate, unaware that every word has already been recorded.",
      zh: "一名残障继承人看着父亲与妻子密谋侵吞母亲的遗产，而他们不知道每一句话都已被录下。"
    },
    warning: {
      en: "Fiction. Contains infidelity, threats and family abuse.",
      zh: "虚构故事。包含婚内背叛、威胁与家庭虐待情节。"
    },
    tone: "violet",
    glyph: "JW",
    content: {
      en: [
        "## Chapter One: The Man in the Wheelchair",
        "I sat in my wheelchair and stared at my wife’s pregnant belly. The child belonged to my own father. The thought made me sick.",
        "After my mother died, the family rotted from its roots. Because I could barely walk, no one treated me as if I mattered. What they did not know was that the entire estate had been my mother’s private property and had been left to me. My father believed he was merely holding it temporarily.",
        "My greedy father had long desired my young wife. She wanted the estate that belonged to me, so she welcomed him. Under my roof they pretended to care while planning to poison my medicine, remove me from the picture and take everything my mother had left.",
        "They believed a disabled man was deaf and blind. But the miniature device inside my wheelchair’s armrest recorded every meeting in the study, every intimate betrayal and every plan to kill me. Each extra day of greed drove another nail into their own coffin.",
        "## Chapter Two: The Last Supper",
        "My father’s birthday banquet was the day they planned to cast me out.",
        "With one arm around my pregnant wife, he performed for the relatives. “My son’s health makes business difficult. From now on, my daughter-in-law will manage the family company for him. She can fulfill the duty he cannot.”",
        "Whispers moved beneath the tables as everyone waited to see the useless heir removed.",
        "I rolled my wheelchair to the enormous projection screen, raised a remote control and pressed one button.",
        "“If we are discussing the estate, let us first see how this devoted wife and loving father planned to divide property that was never theirs.”",
        "The screen did not show financial statements. It showed their secret meetings in the study. Their voices discussed how to kill me and move my inheritance into overseas accounts. Beside the recordings appeared my mother’s notarized will.",
        "The hall became absolutely still. My father’s wineglass shattered on the floor.",
        "## Chapter Three: Kneeling at the Gates",
        "He rushed toward my chair, but police officers entered before he could touch me and pinned him to the floor. My wife saw the paternity report proving that the child was his, together with the clause declaring me the sole heir. She collapsed and began to shake.",
        "“You ungrateful son! You pretended to be helpless so you could trap me!” my father screamed. Against the evidence and the notarized will, however, he was nothing more than a thief.",
        "I rolled closer. “While Mother lived, you did not dare touch her property. The moment she was gone, you joined forces against me and tried to steal what she protected. Today you will learn that this estate is something you cannot recover, even from hell.”",
        "Police carried them away. The assets were frozen and returned to me, their reputations collapsed, and years in prison waited ahead.",
        "I rolled out of the decaying house alone. Sunlight touched my face, and for the first time I could breathe freely. From that day forward, the house was clean.",
        "Dignity is not a gift from someone else. Sometimes it returns only when the people who tried to destroy you finally face judgment.",
        "— End —"
      ],
      zh: [
        "## 第一章：坐轮椅的看客",
        "我坐在轮椅上，看着妻子隆起的肚子。那里怀的是我亲爹的孩子，这种乱了伦理的恶心感让我几度作呕。",
        "母亲过世后，这个家像烂了根的树。我连路都走不稳，家里没人把我当回事。其实这偌大的家产全是母亲生前留给我的私产，只是没有对外公开，父亲一直以为自己只是替我保管。",
        "贪财好色的父亲早就盯上年轻漂亮的妻子；妻子为了吞掉原本属于我的家产，主动投怀送抱。他们在屋檐下假惺惺演戏，背地里盘算在我的药里下毒，让我尽快消失。",
        "他们以为残疾人好欺负，以为我是聋子瞎子。可他们在书房里的勾当和密谋，全被我装在轮椅扶手里的微型设备录得清清楚楚。他们每多贪一天，就是在自己的棺材里多钉一颗钉子。",
        "## 第二章：最后的晚餐",
        "父亲生日宴当天，是他们准备把我扫地出门的日子。",
        "父亲满面红光，搂着怀孕的妻子，当着亲戚假装父慈子孝：“我儿身体不便，以后家里的生意就交给儿媳打理，也算替我那不争气的儿子尽孝。”",
        "亲戚们小声议论，等着看我这个废人被彻底踢出局。",
        "我转动轮椅，停在宴会厅巨大的投影屏幕前，当着所有人的面按下遥控器。",
        "“既然要谈家产，不如先看看这位贤惠儿媳和好父亲，准备怎么瓜分本该属于我的遗产。”",
        "屏幕亮起，画面里是他们在书房里的下流勾当，还有商量如何弄死我、把遗产转到海外账户的录音，以及母亲当年立下的遗嘱公证书。",
        "整个大厅鸦雀无声，只剩父亲的红酒杯摔在地上。",
        "## 第三章：跪着入地狱",
        "父亲冲过来想抢轮椅，还没碰到我就被赶来的警察按在地上。妻子看到证明孩子属于父亲的亲子鉴定，以及写明家产仅由儿子继承的遗嘱，直接瘫在地上发抖。",
        "“你这个逆子，居然装疯卖傻害我？”父亲叫喊着，可在厚厚的证据和法律遗嘱面前，他只是一个窃贼。",
        "我盯着他们，声音冰冷：“母亲活着时你们不敢作妖，她刚走你们就想偷走她留给我的东西。今天我要让你们知道，这百亿家产，你们在地狱里也换不回来。”",
        "警车停在门口，把他们带走。家产被冻结并归还给我，颜面尽失的两人将面对漫长牢狱。",
        "我独自滑着轮椅走出那栋烂房子。阳光照在身上，我第一次觉得呼吸如此顺畅。从今天起，这个家终于干净了。",
        "尊严不是靠谁给的。把那些想害你的人送上审判席，才能真正拿回来。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "a-fathers-final-dignity",
    fileNo: "A-005",
    title: { en: "A Father’s Final Dignity", zh: "亲爹最后的尊严" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "Layla begs doctors to save her father while her stepmother steals his company—until a secret trust clause turns the hospital corridor into a courtroom.",
      zh: "蕾拉在医院哀求医生救父，后妈却趁机侵吞公司；一条秘密信托条款让病房走廊变成审判现场。"
    },
    warning: {
      en: "Fiction. Contains medical coercion, attempted financial abuse and violence.",
      zh: "虚构故事。包含医疗胁迫、财产侵害与暴力情节。"
    },
    tone: "teal",
    glyph: "FD",
    content: {
      en: [
        "## Chapter One: The Calculation at His Bedside",
        "“Doctor, please reconnect my father’s ventilator. I will find the money today—I promise.”",
        "Beside a cold bench in the ICU corridor, Layla knelt and held the physician’s coat. Before he could answer, a hand with blood-red nails slapped a voluntary withdrawal-of-treatment form across her face.",
        "“Stop pretending to be a devoted daughter,” said her stepmother, Anna, wrapped in expensive fur. “I am his legal spouse. I signed the order to stop treatment two hours ago.”",
        "Layla stared at the trembling fingerprint on the form. “He could still speak yesterday. He wanted to live. You stopped paying so your lover could take control of his company.”",
        "The tall man behind Anna—both a major shareholder and her secret partner—placed a custom-made shoe on Layla’s wallet and the medical checks she had gathered, then ground them into scraps.",
        "“Your father is finished. Anna and I control the company now. His shares and the trust your grandfather left you were reorganized five minutes ago. You cannot even afford the morgue, so how do you plan to fight us?”",
        "Directors and relatives lined the corridor, looking down at their phones and pretending not to witness the theft. Anna took her lover’s arm. “Tell the morgue to send him directly for cremation.”",
        "Layla stood, wiped away her tears and removed an encrypted drive from her bag. It played a recording of Anna and her lover plotting to replace the will and end her father’s treatment. In her other hand was an official order opening an international money-laundering investigation.",
        "“Anna, you forgot the trust’s absolute protection clause. If the original beneficiary is subjected to an abnormal withdrawal of medical care, the trust automatically becomes a litigation fund and liquidates every asset held by the people responsible.”",
        "## Chapter Two: The Secret Clause",
        "The corridor fell silent except for the recorded voices. At the phrase ‘international money-laundering investigation,’ the lover’s face darkened. His cigar cutter hit the floor and his hands began to shake.",
        "“How did you get that recording? The trustees told us the fund was frozen.”",
        "Anna reached for the drive. “Do not listen to her. The old man is dead. The company belongs to us.”",
        "Her lover slapped her. “Be quiet. That trust was designed as a trap for us. Once the abnormal-withdrawal clause is triggered, it calls back every bridge loan made to the company and sends all evidence of our asset transfers directly to the tax authority. We will lose everything and go to prison.”",
        "Layla watched them turn on each other, then pressed Send All on her phone.",
        "## Chapter Three: Total Liquidation",
        "Within seconds, every director’s phone filled with notices from banks and the commercial court. Because the controlling parties were suspected of criminal money laundering, company accounts had been frozen and liquidation had begun.",
        "The directors who had watched in silence surrounded Anna and her lover. Their own assets were now at risk, and their convenient loyalty vanished.",
        "Anna crawled toward Layla. “My daughter, I lost my mind. I will pay for your father’s care. I will call the best specialists. Please withdraw the investigation.”",
        "Her lover ran for the elevator, knowing the charges could keep him in prison for decades. When the doors opened, federal tax investigators and police officers were already waiting. Handcuffs closed around his wrists.",
        "Layla turned and entered the ICU. Under the new court order, her father was transferred to the city’s best medical team for protective care.",
        "Within half an hour, authorities sealed Anna’s mansion and vehicles. The empire she had tried to steal disappeared into debt and prosecution. Her lover faced prison, personal liability and the ruin created by his own records.",
        "— End —"
      ],
      zh: [
        "## 第一章：病床前的算计",
        "“医生，我求求你，把我爸爸的呼吸机接回去！医药费我今天一定会凑齐！”",
        "在ICU长廊冰冷的长椅旁，蕾拉跪在地上，死死拽着值班医生的衣角。医生还没说话，一只涂着血红指甲油的手便把自愿放弃治疗同意书甩在她脸上。",
        "“别演孝女了。我是你爸的法定配偶，两小时前已经签字停药。”后妈安娜穿着昂贵皮草，居高临下地看着她。",
        "蕾拉看着同意书上父亲颤抖变形的指印：“他昨天还能说话，明明想活下去。你为了让情人接管公司，故意断掉他的医药费！”",
        "后妈身后的高大男人既是公司大股东，也是她的地下情人。他用定制皮鞋踩住蕾拉的钱包和医疗费支票，将其碾成碎屑。",
        "“你爸已经是废人。公司现在由我和安娜说了算。他的股份和你外公留下的信托，五分钟前已经完成重组。你连太平间都付不起，拿什么跟我们斗？”",
        "几位董事和亲戚低头看手机，假装没看见这场掠夺。安娜挽着情人的手臂转身：“通知太平间，直接拉去火化。”",
        "蕾拉站起来擦干眼泪，从背包拿出正在播放录音的加密U盘，以及税务总局的跨国洗钱调查令。录音里清楚传出后妈和情人偷换遗嘱、给父亲停药的密谋。",
        "“安娜，你忘了外公设立的信托有一条绝对保护条款。只要原始受益人遭遇非正常医疗放弃，信托就会自动变成诉讼基金，全面清盘责任人名下的资产。”",
        "## 第二章：秘密条款的威力",
        "长廊瞬间安静，只剩录音里贪婪的对话。情人听到跨国洗钱调查令，脸色铁青，手里的雪茄剪掉在地上。",
        "“你怎么会有录音？信托的绝对保护条款……那群老家伙不是说资金早就冻结了吗？”",
        "安娜试图抢夺U盘：“别听她吓唬人！老头子已经死了，公司是我们的！”",
        "情人反手抽了安娜一巴掌：“闭嘴！那个信托就是老头为了防备我们设下的死局。一旦触发条款，信托会收回所有过桥资金，把资产转移证据送给税务局。我们不只会破产，还会坐牢！”",
        "蕾拉冷冷看着他们狗咬狗，按下手机的群发键。",
        "## 第三章：绝对清盘",
        "几秒内，董事和亲戚的手机疯狂闪烁。商业法庭和银行通知显示：公司核心控股方涉嫌刑事犯罪及恶意洗钱，全部流水账户被冻结，进入破产清算。",
        "原本冷眼旁观的董事利益受损，瞬间将安娜和情人围在中间。",
        "安娜爬向蕾拉：“亲闺女，我鬼迷心窍！我出你爸爸的医药费，马上联系最好的专家，求你撤回调查令！”",
        "情人知道洗钱罪足以让自己坐穿牢底，连滚带爬逃向电梯。电梯门一开，联邦税务稽查员和警察已经等在那里，手铐瞬间锁住他的双手。",
        "蕾拉推开ICU大门。在司法介入下，父亲被紧急转入全市最好的医疗团队接受保护性救治。",
        "半小时后，后妈和情人的豪宅、豪车全部被贴上封条。安娜面对巨债和牢狱，人生彻底崩塌；她的情人不仅一无所有，还将背负无法偿还的个人债务，在铁窗里度过余生。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-last-watchman",
    fileNo: "A-002",
    title: { en: "The Last Watchman", zh: "最后的守夜人" },
    category: { en: "Justice & Reckoning", zh: "正义审判" },
    summary: {
      en: "A confused old man in a wheelchair is attacked for entertainment, but the medal in his fist carries the weight of a nation’s final line of defense.",
      zh: "一位坐在轮椅上的失智老人被街头混混羞辱，而他紧握的勋章承载着国家最后一道防线。"
    },
    warning: {
      en: "Fiction. Contains elder abuse and violence.",
      zh: "虚构故事。包含虐待老人及暴力情节。"
    },
    tone: "blue",
    glyph: "LW",
    content: {
      en: [
        "## Chapter One: The Revelry of Small Men",
        "No one would have guessed that the chief scientist who once held authority over the nation’s strategic nuclear defenses could be tormented like a stray dog by a pack of reckless street thugs.",
        "I sat in my wheelchair and watched them laugh. The humiliation suffocated me more than death. My wife was gone, and my only son had died on a national project. On this broken street, no one knew who I was.",
        "They tipped my wheelchair into a heap of wet garbage, poured beer over my aging body and filmed themselves laughing. I no longer understood why they were hurting me. I only knew to protect myself, and every attempt made them strike harder. My coat was torn, but my fist never opened. Inside it was the National Defense Medal, an honor once treated with the authority of the president himself.",
        "They uploaded my struggle for clicks. “Look at the old wreck twitching for a bone,” one of them said.",
        "They could not understand that the disabled man beneath their shoes had once spoken codes capable of placing the nation’s entire strategic shield on alert. Now I was trapped inside a failing and confused body, watching small men grind the memory of that life into the mud.",
        "## Chapter Two: The Price of Crossing the Line",
        "On Tuesday afternoon, their leader snatched my last hamburger, crushed it under his shoe and ordered the others to strip off the old coat that still carried a classified identification plate.",
        "A new neighbor, Mrs. Mary, saw everything. Too frightened to intervene, she called the police with shaking hands. “Please… some young men are attacking an old man. He seems confused, but there is something different about him. You have to come now.”",
        "The first officers treated the incident as routine. Then an experienced sergeant pulled open my torn coat and saw the code engraved on the identity plate. One search of that number could place the entire federal security service on its highest alert.",
        "## Chapter Three: The Reckoning",
        "The sergeant’s face went white. He could barely speak as he called his superiors.",
        "Less than ten minutes later, brakes screamed along the street. More than a dozen black armored vehicles arrived, followed by heavily armed special forces. The block was sealed, helicopters circled overhead, and searchlights turned night into day.",
        "The thugs were still showing off their trophies when rifles forced them to their knees. Then they watched officers they had only ever seen on television stand before the dazed old man in the wheelchair and deliver a formal salute.",
        "The commanding general knelt beside me, straightened my collar and faced the trembling attackers. “The man you humiliated built this country’s final shield. Without him, you would not even possess the freedom you used to abuse him.”",
        "## Chapter Four: The Last Dignity",
        "The attackers were taken away to face charges for abusing one of the nation’s highest-honored servants and compromising national security. Their future would be decided in federal court.",
        "I was quietly returned to a secure medical center. Still lost inside fragments of memory, I pointed at the stars and told a guard, “We must calculate the angle correctly, or the Mars rover will miss its landing.”",
        "Behind me, the general straightened his back and saluted once more.",
        "Some lights do not fade with time. Those who stamp on the final ember may discover that the darkness remembers exactly who they are.",
        "— End —"
      ],
      zh: [
        "## 第一章：蝼蚁的狂欢",
        "谁敢想，曾手握美国最高战略核武器控制权的首席科研家，现在竟被几个不知死活的小混混欺负得像条狗。",
        "我坐在轮椅上，看着那群对着我狂笑的混混。这种屈辱比死亡更让我窒息。老伴病逝，唯一的儿子也为了国家项目殉职，我成了孤家寡人。在这条烂街道上，没人知道我是谁。",
        "小混混把我的轮椅掀翻在满是臭水的垃圾堆里，往我苍老的身体上泼啤酒，一边拍视频一边嘲笑。我不知道他们为什么打我，只会本能地保护自己，可我越反击，他们打得越狠。衣服被撕成破布，我却始终攥着那枚代表国家最高荣誉的安全防卫勋章。",
        "他们把我的挣扎发到社交媒体上博取点击：“看这个老废物，反抗的样子像不像一条为了啃骨头抽搐的死狗？”",
        "他们不会理解，被他们踩在脚下取乐的人，曾经只用一个代号就能让整个国家的战略防线进入战备。如今我被困在衰朽、糊涂的躯壳里，只能看着这群蝼蚁把昔日站在云端的人碾进泥里。",
        "## 第二章：越界的代价",
        "周二下午，混混头目抢走我仅剩的汉堡，用脚踩碎。他们围着我起哄，试图扒下那件缝着绝密铭牌的破外套。",
        "新搬来的邻居玛丽太太看见了一切。她不敢直接干预，却颤抖着拨通报警电话：“求求你们，那几个孩子在霸凌一个老人。老头看起来不太对劲，但我感觉他不一样。你们必须马上过来。”",
        "警察起初没有当回事，直到一名经验丰富的警长扯开旧外套，看见内侧刻着高密级代号的身份铭牌。那个编码一经查询，足以让整个联邦调查系统进入最高戒备。",
        "## 第三章：来自地狱的肃清",
        "警长脸色惨白，立刻向上级紧急汇报。",
        "不到十分钟，街道响起刺耳的制动声。十几辆黑色装甲越野车赶到，全副武装的特种部队封锁街区，武装直升机在低空盘旋，探照灯把黑夜照成白昼。",
        "几个混混还没反应过来，就被枪口逼着跪下。他们看着平日只在新闻里出现的军官，对着轮椅上神情木讷的老人整齐敬礼。",
        "带队将军单膝跪下，替我理好衣领，对瑟瑟发抖的混混怒吼：“你们羞辱的，是为这个国家撑起最后一道屏障的人。没有他，你们连叫嚣的自由都不会有！”",
        "## 第四章：最后的尊严",
        "混混被带走，将在联邦法庭面对危害国家安全及虐待国家顶级功勋人员的重罪。",
        "我被秘密接回军事禁区内的特级疗养院，依旧糊涂地指着窗外星空对守卫说：“角度要算准，不然火星车落不下去。”",
        "将军站在我身后，再次挺直脊梁向我敬礼。",
        "世上总有一些光，不会因岁月流逝而暗淡。试图践踏残灯余火的人，终会被黑夜吞噬。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-logic-of-a-beast-in-the-mire",
    fileNo: "A-006",
    title: { en: "The Logic of a Beast in the Mire", zh: "泥潭里的畜生逻辑" },
    category: { en: "Social Justice", zh: "社会正义" },
    summary: {
      en: "A racist tycoon humiliates Marcus before a cheering crowd, unaware that his victim is the investigator who has spent three years dismantling the empire.",
      zh: "一个种族主义富豪当众羞辱马库斯，却不知道眼前的受害者正是调查他三年的人。"
    },
    warning: {
      en: "Fiction. Contains racist abuse, slurs and graphic violence.",
      zh: "虚构故事。包含种族歧视言论、侮辱性用语及强烈暴力描写。"
    },
    tone: "ink",
    glyph: "MJ",
    content: {
      en: [
        "“You filthy animal crawling in the mud. Who allowed a Black man like you into my estate?”",
        "To Carter, racism was another way to display power. He seized Marcus by the hair and forced him to kneel beside the champagne glasses. Then he smashed a crystal tumbler of liquor and spit into Marcus’s face. Blood blurred Marcus’s vision.",
        "Carter kicked him, ordered guards to throw his clothes into a sewage pipe and tossed urine-soaked banknotes across his face. “This is where your kind belongs. A suit cannot wash away what you are. Lick the mud from my shoes or I will ruin you and have your daughter expelled from every elite school in the city.”",
        "He started a livestream and tried to force Marcus to call himself an inferior human being. Each word and deliberate cruelty crossed another moral line while guests cheered.",
        "Pinned to the cold floor, Marcus tasted blood. At the moment his body appeared to give in, a high-frequency alarm sounded from his torn pocket. A blood-marked tablet lit up, revealing every surveillance feed from the estate’s control room.",
        "Carter continued waving a check. He did not notice that the ballroom screens had frozen. Then his recorded order to ‘remove every Black employee’ from the business was pushed live across the internet.",
        "## Chapter Two: The Investigators Arrive",
        "The ballroom went dark. Red emergency lights began to rotate.",
        "“Who dares interfere with my estate?” Carter shouted. Two armored vehicles smashed through the alloy gates, and dozens of agents from the Federal Special Audit Bureau entered through the dust, every weapon trained on him.",
        "“Drop everything and place your hands on your head.” The command shattered the party’s illusion of luxury.",
        "Carter demanded to file a complaint. The commanding officer ignored him, walked to Marcus, knelt and saluted. “Sir, the three-year investigation into Carter Group’s racial-purification program and international money laundering is complete. The Department of Justice is taking control of all assets immediately.”",
        "A thick case file landed at Carter’s feet. Page after page documented discriminatory directives, hidden accounts and criminal conduct.",
        "Marcus stood, removed the senior investigator’s badge from his collar and held it beneath the ballroom lights.",
        "“You asked what gave me the right to enter,” Marcus said, replacing the jacket stained dark with wine and blood. “I came to watch your so-called superior empire collapse beneath the evidence.”",
        "## Chapter Three: An Empire Falls",
        "Every powerful guest’s phone vibrated at once. Global financial systems had issued an absolute freeze.",
        "Carter Group’s overseas credit, listed-company guarantees and personal accounts dropped to zero. In one moment, the billionaire became a defendant carrying billions in liabilities.",
        "Guests who had flattered him turned away, desperate to prove that they had not participated. Federal officers separated the crowd and took Carter into custody as the party disintegrated around him.",
        "Marcus stopped beside the armored transport. “You built your worth around skin color. Now the law will measure you by your actions.”",
        "The estate was sealed as the convoy departed. Behind the vehicle’s barred window, Carter’s arrogance had become fear. Prison, prosecution and public disgrace waited where his manufactured superiority had once stood.",
        "Dignity never needs skin color to prove itself. It belongs to those who refuse to let cruelty define their place in the world.",
        "— End —"
      ],
      zh: [
        "“你这头在泥里爬的脏畜生，也敢让这种黑皮猪踏进我的庄园？”",
        "种族歧视在卡特眼里只是彰显权力的入场券。他揪住马库斯的头发，强迫他跪在香槟杯旁，将兑了痰的烈酒连同水晶杯砸进马库斯眼眶。鲜血瞬间模糊了视线。",
        "卡特命令保镖把马库斯的衣服扔进排污管，再把带着尿骚味的现金砸在他脸上：“这才是你们这种低贱种族的位置。除非你像狗一样舔干净我的鞋，否则我不仅要废了你，还要让你刚入学的女儿被全城精英学校赶走！”",
        "卡特掏出手机直播，逼迫马库斯在镜头前承认自己是低等生物。他每一个字、每一个动作都在挑战人类道德底线，围观宾客却兴奋地尖叫。",
        "马库斯被按在冰冷地板上，嘴里全是腥味。就在他似乎彻底绝望时，破烂口袋里突然传出高频警报。带血的平板电脑自动亮起，显示出庄园主控室的全部监控画面。",
        "卡特还在挥舞支票，却没发现巨型屏幕上的酒会画面突然卡顿。紧接着，他半小时前下令清洗所有黑人雇员的通话录音被同步推向全网。",
        "## 第二章：审判者降临",
        "大厅灯光骤然熄灭，红色紧急警报灯疯狂旋转。",
        "“谁敢动我的庄园？”卡特的咆哮还没落地，两辆装甲车撞开合金大门。烟尘中，几十名联邦特别审计局特勤人员鱼贯而入，枪口全部锁定卡特。",
        "“放下武器，双手抱头！”命令瞬间击碎酒会的奢靡幻象。",
        "卡特还在叫嚷投诉，带队长官却径直走向马库斯，单膝跪地敬礼：“长官，针对卡特集团长达三年的种族纯化计划及跨国洗钱调查已经结案，所有资产即刻由司法部门接管。”",
        "厚厚的卷宗落在卡特脚边，每一页都是他的歧视记录和犯罪证据。",
        "马库斯缓缓站起，从领口摘下特级调查官勋章。",
        "“你问我凭什么进来？”马库斯披上被红酒和鲜血染红的外套，“我来这里，是为了亲眼看着你所谓优越的帝国，如何在证据面前崩塌。”",
        "## 第三章：帝国崩塌",
        "庄园内所有人的手机同时震动，全球金融中心发出绝对熔断通知。",
        "卡特集团的海外信贷、上市担保和个人账户在这一刻全部冻结。他从亿万富翁变成背负数十亿债务、面临终身监禁的被告。",
        "刚才还点头哈腰的权贵为了证明清白，纷纷与他切割。特勤人员隔开人群，在混乱中将卡特依法拘捕。",
        "马库斯在防暴车旁停下：“你最看重肤色，现在法律只会按照你的行为来衡量你。”",
        "车队驶离，辉煌庄园被贴上法院封条。铁窗后的傲慢只剩恐惧，等待卡特的是漫长牢狱、司法追责与公开审判。",
        "尊严从来不需要靠肤色证明。它属于每一个拒绝让暴行定义自己位置的人。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-viper-in-the-nest",
    fileNo: "A-007",
    title: { en: "The Viper in the Nest", zh: "温床上的毒蛇" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "A pregnant woman watches her husband and sister build a secret life inside her home, quietly saving every message until the day they demand her property.",
      zh: "一名孕妇看着丈夫和妹妹在自己家里构筑秘密关系，默默保存证据，等待他们逼她交出财产的那一天。"
    },
    warning: {
      en: "Fiction. Contains infidelity, threats, pregnancy loss and violence.",
      zh: "虚构故事。包含婚内背叛、威胁、流产与暴力情节。"
    },
    tone: "green",
    glyph: "VN",
    content: {
      en: [
        "## Chapter One: The Viper in the Nest",
        "Pregnancy made me sleep deeply. Every night after I drifted off, the man beside me rose quietly, crossed the hallway and opened my sister’s bedroom door.",
        "They believed their arrangement was invisible. At dinner, my sister peeled shrimp for me; in the bathroom, she showed my husband the curve of her own pregnant belly. Together they built a net inside my family. He moved assets while she prepared to take control after giving birth. Their final plan was to label me with postpartum depression, send me to a facility and throw me out of my own home.",
        "They treated me as a tool in their betrayal and repeatedly brought me bowls of what they called nourishing soup.",
        "I never drank it. I watched their performance and their dream of wealth with quiet amusement. A hidden camera had already been installed inside my wardrobe, and every private conversation was synchronized to my cloud archive.",
        "They called it love. I saw two mice dancing their final waltz on the road to a trap.",
        "## Chapter Two: The Final Threat",
        "My due date arrived, and they chose it as the day to confront me.",
        "My sister entered the bedroom in a carefully chosen maternity dress. My husband followed, and the gentleness he used to wear had disappeared from his face.",
        "“Stop pretending,” he said, gripping my wrist hard enough to hurt the bone. “Sign over the property and the shares. If you resist, I will kill the child inside you and leave you to spend the rest of your life with the guilt.”",
        "My sister stared at my stomach. “Do not blame us. Blame yourself for refusing to give up your place. That child will only be another burden nobody wants.”",
        "I sat at the edge of the bed and smiled. Outside the window, dozens of black enforcement vehicles had already sealed the estate.",
        "“Everything you want is here.” I placed a stack of documents on the bed.",
        "They reached for it, expecting an inventory of property. The first page showed a paternity report, records of illegal fundraising, and a signed complaint documenting long-term abuse and an attempt to harm my unborn child.",
        "The front doors crashed open.",
        "## Chapter Three: Destruction and Judgment",
        "A special enforcement team flooded the villa. Faced with the officers, my sister broke down. During the struggle she suddenly folded over in pain, blood spreading beneath her dress.",
        "“My baby…” she cried from the floor.",
        "My husband collapsed. Pointing at her, he screamed, “It was all her idea. She was jealous of her sister. She planned everything. I am a victim too.”",
        "To save himself, he pushed every crime onto the woman he claimed to love. Their unborn child—once used as an instrument for power—became the first casualty of their collapse. The law would decide the rest.",
        "“Mr. Lin and Ms. Su, you are under arrest on suspicion of commercial fraud, bigamy and conspiracy to commit murder.”",
        "They were taken away. My sister received emergency treatment but still faced prosecution; my husband kept bargaining and denying responsibility.",
        "Their accounts were sealed and their supposed love entered the record as evidence. I would carry my own child forward and cut the last thread tying me to their betrayal.",
        "As officers led them to the vehicles, I offered one final sentence. “You wanted this house. Keep it in your dreams. Memories are the only property you can take into prison.”",
        "Dignity is not proved by birth or status. It is reclaimed when cruelty no longer controls the door to your own home.",
        "— End —"
      ],
      zh: [
        "## 第一章：温床上的毒蛇",
        "我睡得很沉，因为这是怀孕后的常态。每晚在我睡着后，枕边的男人都会轻手轻脚起身，穿过走廊，推开妹妹房间的门。",
        "他们以为这场地下交易天衣无缝。餐桌上，妹妹会贴心地为我剥虾，转头却在洗手间向我丈夫炫耀她已经显怀的肚子。他们在我的家庭里编织捕网：丈夫转移资产，妹妹准备在生产后夺取家庭主权，最后再以产后抑郁为由将我送进疗养院。",
        "他们把我当成这场伦理悲剧里的工具人，还时不时让我喝下所谓的补汤。",
        "但我从不喝。我看着他们自导自演，只觉得好笑。卧室衣柜里早已装好高清针孔摄像头，所有亲密聊天记录也同步上传到我的云端备份。",
        "他们以为这是爱情，其实只是两只老鼠在通往捕鼠夹的路上跳最后一场华尔兹。",
        "## 第二章：最后的胁迫",
        "预产期到了，这是他们决定摊牌的日子。",
        "妹妹穿着精心挑选的孕妇裙走进卧室，丈夫跟在身后，原本温文尔雅的脸上只剩毫不掩饰的狰狞。",
        "“别装了。”丈夫猛地掐住我的手腕，“把房产证和股权转让书签了。你敢反抗，我就亲手弄死你肚子里的孩子，让你下半辈子在绝望里赎罪！”",
        "妹妹恶毒地盯着我的肚子：“姐姐，别怪我们。要怪就怪你占着位置不让。反正这个孩子生下来也是没人要的累赘。”",
        "我坐在床边平静地笑了笑，望向窗外——几十辆司法执行局的黑色轿车已经封锁整个庄园。",
        "“你们想要的，都在这里。”我把一叠资料扔在床上。",
        "他们以为那是财产清单，欣喜若狂地扑过去。第一页却是亲子鉴定、非法集资记录，以及证明他们长期密谋虐待并试图伤害胎儿的实名举报信。",
        "砰的一声，别墅大门被撞开。",
        "## 第三章：毁灭与审判",
        "特勤小组涌入。妹妹看到枪口后瞬间崩溃，在挣扎中痛苦地捂住肚子，鲜血顺着裙底蔓延。",
        "“我的孩子……”她面色惨白，在地上哀嚎。",
        "丈夫吓得瘫软，指着她歇斯底里地喊：“不是我，全是她！她嫉妒姐姐，是她策划一切毁掉这个家。我也是受害者！”",
        "为了保命，他把所有罪责推给曾经口口声声说爱的人。那个被他们当作夺权工具的孩子，成了权力崩塌中的第一个牺牲品；其余的，将由法律审判。",
        "“林先生、苏小姐，你们涉嫌商业诈骗、重婚及教唆谋杀，立刻跟我们走。”",
        "妹妹被紧急送医，却依然难逃司法追责；丈夫不停撇清关系，企图换取宽大处理。",
        "他们的资金全部被查封，所谓爱情成了法庭证据。我会带着自己的孩子，彻底切割这段令人作呕的过去。",
        "被押上车前，我最后对他们说：“这套房子留给你们做梦吧，因为那是你们在监狱里唯一能带走的东西。”",
        "尊严不需要靠出身证明。它来自把欺凌者挡在自己人生门外的勇气。",
        "—— 全文完 ——"
      ]
    }
  }
];
