window.STORY_ARCHIVE = [
  {
    slug: "the-broken-home",
    fileNo: "A-001",
    title: { en: "The Broken Home", zh: "家宴上的囚徒" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "Hours after leaving the hospital, Eva is pressured to sign away her marriage at a family banquet—until she reveals the documents that can bring the entire dynasty down.",
      zh: "刚离开医院的伊芙被带到家宴上逼迫离婚，直到她拿出足以让整个家族崩塌的文件。"
    },
    warning: {
      en: "Fiction. Contains family conflict, coercion and medical distress.",
      zh: "虚构故事。包含家庭冲突、胁迫与医疗困境。"
    },
    tone: "rust",
    glyph: "BH",
    content: {
      en: [
        "## Chapter One: The Banquet",
        "“Sign the divorce papers. After what happened at the hospital, you no longer have a place at our family’s table.”",
        "At the center of a lavish banquet attended by more than a hundred family members and executives, Eva’s mother-in-law placed a stamped hospital report in front of her. Eva had left the hospital only hours earlier and was still weak.",
        "“Mom… I went through a medical emergency this morning. You brought your son’s new partner here and now you are forcing me out in front of the whole family?” Eva steadied herself against a chair, still weak from the hospital.",
        "The husband she had loved for seven years did not even look up. Sitting beside his new partner, Thomas calmly cut his steak. “If my mother tells you to sign, then sign. Take the divorce and leave.”",
        "His mother snatched the papers from Eva’s hand. Around the table, relatives and executives who had always pretended to be kind watched without lifting a hand. A few even laughed.",
        "“This is your last day here,” the older woman said. “Guards, escort her out.”",
        "Eva remained calm. She pulled three stamped bank demand notices and a receipt from the tax authority out of her bag. Then she looked directly at Thomas.",
        "“You seem to have forgotten that the mansion, the Rolls-Royce and every guarantee behind your company’s listing are in my name. I faced the hardest morning of my life, and now you want me to sign away my marriage at this table. Fine. We can face the consequences together.”",
        "## Chapter Two: The Only Card Left",
        "The room went silent. Thomas’s silver pen slipped from his hand. He reached for the papers and read the official stamps, finally understanding what the evidence meant.",
        "“No. This cannot be real. When did you revoke the guarantees? And this tax audit…”",
        "His mother still did not understand. “Why are you afraid of her? The company is listed. We are rich now.”",
        "“Be quiet!” Thomas screamed. “Every bridge loan for the listing was secured against this house and my shares. The house is in Eva’s name. Every primary loan and personal guarantee depends on her credit.”",
        "Holding the edge of the table, Eva rose inch by inch. It hurt, but she stood with more dignity than anyone else in the room.",
        "“You moved marital assets, broke our marriage agreement and interfered with my medical care. Did you truly think I knew nothing? I stayed silent because I hoped our family could still be repaired. This morning’s emergency ended that hope.”",
        "## Chapter Three: Nothing Left",
        "Eva put her phone on speaker. The chief legal officer of the city’s largest commercial bank answered.",
        "“Ms. Eva, following the divorce petition and evidence of malicious transfer of marital property that you submitted one hour ago, we have applied for pretrial asset preservation. Because you withdrew your joint personal guarantee, the company’s credit facility was automatically suspended five minutes ago.”",
        "Phones began chiming around the room. The notices all said the same thing: the controlling shareholder was suspected of fraud and serious marital misconduct; company accounts were frozen, the listing was halted, and liquidation proceedings were beginning.",
        "The relatives and executives who had mocked Eva suddenly turned on Thomas. Their own money was trapped. “You have ruined us!” one shouted. “Why did you provoke her?” cried another.",
        "Thomas rushed toward Eva. “I was wrong. My mother pressured me. Please restore the guarantee.” He reached for the papers she had placed on the table.",
        "Thomas’s new partner saw the plan collapse and quietly left the room.",
        "Eva never looked back. Wrapped in a thin hospital gown and accompanied by police officers and her lawyers, she walked out of the mansion that had held seven years of her pain.",
        "Half an hour later, the court sealed the front gate. Thomas’s mother collapsed under the weight of the debt. Thomas lost the company, the house and every privilege he had taken for granted. Millions in personal liabilities would follow him for the rest of his life.",
        "— End —"
      ],
      zh: [
        "## 第一章：家宴上的囚徒",
        "“把离婚协议签了。医院发生那件事以后，你已经不适合继续留在我们家的宴席上。”",
        "在上百名家族成员和公司高管齐聚的宴会上，婆婆把一份盖着红印的医院报告放到伊芙面前。伊芙刚离开医院几个小时，身体仍然十分虚弱。",
        "“妈……我今天早上刚经历了一场医疗意外。你为了让另一个女人进入这个家，竟然当着全家族的面逼我离开？”伊芙扶住椅背，身体仍然十分虚弱。",
        "她爱了七年的丈夫托马斯坐在新伴侣身边，连头都不抬：“我妈让你签你就签。签了字，离开这里。”",
        "婆婆从伊芙手中夺走协议书。周围平日和蔼的亲戚和集团高管无人阻拦，甚至有人发出刺耳的笑声。",
        "“你今天必须离开。保镖，把她带出去！”",
        "伊芙保持平静，从包里拿出三份盖章的银行催缴通知书和一份税务部门的回执，直视丈夫和婆婆。",
        "“托马斯，你忘了这栋豪宅、劳斯莱斯，还有你公司上市的所有担保人，写的都是我的名字。我刚经历人生最艰难的早晨，你们就在桌上逼我离婚。那我们现在就一起面对后果吧。”",
        "## 第二章：底层的底牌",
        "全场安静下来。托马斯手里的银色钢笔掉在地上。他拿起单据，看清官方印章后，终于明白这些证据意味着什么。",
        "“不……这不可能！你什么时候撤销了担保？还有这个税务审计……”",
        "婆婆仍不理解：“儿子，你怕她干什么？公司都上市了，我们现在有钱了。”",
        "“妈，你闭嘴！”托马斯绝望地咆哮，“公司上市的所有过桥资金，全用这栋房子和我的股份抵押。而房子写的是伊芙的名字，所有主贷人和信用担保都靠她的个人信用！”",
        "伊芙扶着桌角，一寸一寸、极其艰难却无比尊严地站起来。",
        "“你转移资产、违反婚姻承诺，还干预我的医疗安排。你真以为我什么都不知道？我沉默，是因为希望这个家庭还有修复的可能。今天早上的意外，让这份希望结束了。”",
        "## 第三章：一无所有",
        "伊芙拿出手机，当着全场亲戚和高管按下免提。电话那头是本地最大商业银行的首席法务代表。",
        "“伊芙女士，根据您一小时前提交的离婚诉讼及婚内财产恶意转移证明，我们已向法院申请诉前财产保全。由于您撤销了对托马斯先生公司的个人连带担保，公司的信用额度已在五分钟前自动熔断。”",
        "全场手机疯狂响起：大股东涉嫌欺诈，公司账户被冻结，上市程序中止，并将进入全面清算。",
        "原本冷眼旁观的亲戚和高管发现自己的投资也受影响，纷纷要求托马斯解释。",
        "托马斯慌忙冲过来：“我错了，是我妈逼我的！求你把担保拿回来！”他伸手想夺回桌上的文件。",
        "托马斯的新伴侣看见计划失败，安静地离开了宴会厅。",
        "伊芙没有再看他们。她裹紧单薄的医院外套，在警察和律师陪同下，一步一步走出这栋留下太多痛苦回忆的别墅。",
        "半小时后，法院封条贴上别墅大门。相关资产进入司法清算；托马斯不仅失去公司控制权，还将面对数千万个人债务。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "cleaning-house",
    fileNo: "A-003",
    title: { en: "Cleaning House", zh: "清理门户" },
    category: { en: "Justice & Reckoning", zh: "正义审判" },
    summary: {
      en: "A young heir pushed to the edge of his own family waits three years to reveal the ledger that proves who stole his inheritance and dismantled his father’s company.",
      zh: "一个被家族排斥的年轻继承人隐忍三年，终于拿出证明遗产被盗、父亲公司被侵吞的完整账目。"
    },
    warning: {
      en: "Fiction. Contains guardianship abuse, coercion and family conflict.",
      zh: "虚构故事。包含监护权滥用、胁迫与家庭冲突。"
    },
    tone: "gold",
    glyph: "CH",
    content: {
      en: [
        "I stood beside the dining table while my uncle deliberately kept the final chair empty, making it clear that I was not welcome in my own family home.",
        "Above me, his family of three drank the wine my father had loved. Tonight it was their victory bottle, opened to celebrate removing me from my own inheritance.",
        "“Call me Dad,” my uncle said with a cold smile. “Do that and perhaps I will let you remain at this table. Your father is no longer here to protect your place.”",
        "I stared back without tears. Since the court placed me in their care, I had been treated like an unwanted guest. My aunt cut her food with perfect elegance and never once looked at me.",
        "“When your mother left, you became our responsibility,” she said. “And those assets your father left? We consider them payment for everything we have done.”",
        "At last I ran into the rain. I became ill at an intersection, and the police returned me to their house. When the door closed, my uncle opened a drawer, removed a camera and led me into his study for what he called a ‘formal assessment.’",
        "He wanted a recording that could be edited to make me appear incapable of managing my affairs. With it, he planned to challenge my inheritance claim.",
        "Before he could aim the camera, the study door opened. The company’s former finance director entered with two lawyers. He ignored my uncle, placed his jacket over my shoulders and faced me.",
        "“Young master, every account now balances,” he said. “From your grandfather’s generation to the scheme that removed your father from his own company, every movement of money is documented in this encrypted archive.”",
        "I stood, walked to the camera and pressed Delete. Then I turned toward the couple whose faces had gone gray.",
        "“Which one of us did you say had no place here?”",
        "For three years I had moved quietly through the company’s records, documenting every account they used against me. I never needed revenge. I simply placed their decisions before the law.",
        "When the final liquidation agreement was placed before my uncle, court seals went onto the villa that had once confined me. I watched him sign while his wife asked me to leave them a small allowance.",
        "I entered the car and started the engine. In the mirror, they stood in the middle of an empty street, no longer able to control my life.",
        "Dignity does not need to be argued for. Once you become the author of the rules, everyone who stood on your head eventually begs you to move your foot.",
        "— End —"
      ],
      zh: [
        "我站在餐桌旁，姑父故意让最后一把椅子空着，明摆着告诉所有人：在这个家里没有我的位置。",
        "餐桌上，他们一家三口正在享用红酒。那是父亲生前最爱的一款，如今却成了姑父庆祝把我踢出遗产继承权的庆功酒。",
        "“叫我一声爸。”姑父带着冷笑说，“你肯配合，我或许还能让你留在这张桌子旁。你父亲已经不在，没人能替你保住位置。”",
        "我没有流泪。法院把我交给他们照顾之后，我便成了这个家里不受欢迎的客人。姑姑优雅地切着食物，始终不肯看我一眼。",
        "“你母亲离开后，我们承担了你的生活。”她说，“至于你父亲留下的资产，就当作这些年的补偿。”",
        "我跑进雨里，在路口病倒，又被警察送回他们家。门关上后，姑父从抽屉里拿出摄像机，把我带进书房，声称要做一次‘正式评估’。",
        "他想剪辑一段让我看起来没有能力管理个人事务的录像，再借此挑战我的继承资格。",
        "镜头还没打开，书房门便被推开。公司曾经的老财务总监带着两名律师走了进来。他没有理会姑父，只把外套披在我的肩上。",
        "“少爷，账目全部对齐了。”老人说，“从你爷爷那一代，到你父亲被排挤出公司的过程，所有资金流转都记录在这个加密档案里。”",
        "我站起来，走到摄像机前按下删除键，再看向那对终于意识到计划失败的夫妻。",
        "“你们刚才说，谁没有资格留在这里？”",
        "三年来，我一直安静地整理公司记录，记下他们对每个账户做过的决定。我不需要报复，只需要把证据交给法律。",
        "最后一份资产清算协议放到姑父面前时，曾限制我自由的别墅被贴上法院封条。我看着他在协议上签字，他的妻子则请求保留一小笔生活费用。",
        "我坐进车里发动引擎。倒车镜里，他们站在空荡荡的街道中央，再也无法支配我的人生。",
        "尊严不需要靠争吵证明。当你学会用规则保护自己，曾经支配你的人就无法再决定你的位置。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "judgment-from-a-wheelchair",
    fileNo: "A-004",
    title: { en: "Judgment from a Wheelchair", zh: "轮椅上的审判" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "A disabled heir watches his father and wife plan to steal his mother’s estate, unaware that every word has already been recorded.",
      zh: "一名残障继承人看着父亲与妻子密谋侵吞母亲的遗产，而他们不知道每一句话都已被录下。"
    },
    warning: {
      en: "Fiction. Contains family betrayal, coercion and financial abuse.",
      zh: "虚构故事。包含家庭背叛、胁迫与财产侵害情节。"
    },
    tone: "violet",
    glyph: "JW",
    content: {
      en: [
        "## Chapter One: The Man in the Wheelchair",
        "I sat in my wheelchair and listened as my wife praised my father’s latest business plan. Their sudden alliance told me that I had become the obstacle they intended to remove.",
        "After my mother died, the family rotted from its roots. Because I could barely walk, no one treated me as if I mattered. What they did not know was that the entire estate had been my mother’s private property and had been left to me. My father believed he was merely holding it temporarily.",
        "My father wanted permanent control of the company, while my wife wanted the estate. Under my roof they pretended to care while planning to have me declared incapable and move everything my mother had left into accounts they controlled.",
        "They believed a disabled man would never be heard. But the miniature device inside my wheelchair’s armrest recorded every meeting in the study and every plan to remove my legal rights. Each extra day of greed added another page to the case against them.",
        "## Chapter Two: The Last Supper",
        "My father’s birthday banquet was the day they planned to cast me out.",
        "Standing beside my wife, he performed for the relatives. “My son’s health makes business difficult. From now on, my daughter-in-law will manage the family company for him.”",
        "Whispers moved beneath the tables as everyone waited to see the heir removed.",
        "I rolled my wheelchair to the enormous projection screen, raised a remote control and pressed one button.",
        "“If we are discussing the estate, let us first see how this devoted wife and loving father planned to divide property that was never theirs.”",
        "The screen showed their secret meetings in the study. Their voices discussed an edited medical assessment, forged corporate resolutions and plans to move my inheritance into overseas accounts. Beside the recordings appeared my mother’s notarized will.",
        "The hall became absolutely still. My father’s wineglass shattered on the floor.",
        "## Chapter Three: Judgment at the Gates",
        "He rushed toward my chair, but investigators entered before he could reach me. My wife saw the transfer records, together with the clause declaring me the sole heir, and realized that their plan had failed.",
        "“You pretended to be helpless so you could trap me!” my father shouted. Against the evidence and the notarized will, however, he had no legal defense.",
        "I rolled closer. “While Mother lived, you did not dare touch her property. The moment she was gone, you joined forces against me and tried to steal what she protected. Today that estate returns to its lawful owner.”",
        "Authorities escorted them away. The disputed assets were frozen and returned to me, and both of them faced a formal prosecution.",
        "I rolled out of the decaying house alone. Sunlight touched my face, and for the first time I could breathe freely. From that day forward, the house was clean.",
        "Dignity is not a gift from someone else. Sometimes it returns only when the people who tried to destroy you finally face judgment.",
        "— End —"
      ],
      zh: [
        "## 第一章：坐轮椅的看客",
        "我坐在轮椅上，听妻子称赞父亲最新的商业计划。他们突然变得亲密，让我明白：我已经成了他们想要排除的障碍。",
        "母亲过世后，这个家像烂了根的树。我连路都走不稳，家里没人把我当回事。其实这偌大的家产全是母亲生前留给我的私产，只是没有对外公开，父亲一直以为自己只是替我保管。",
        "父亲想永久控制公司，妻子则想拿到遗产。他们在屋檐下假装关心我，背地里却计划让我被认定为没有管理能力，再把母亲留下的资产转进他们控制的账户。",
        "他们以为残障人士不会被听见。可轮椅扶手里的微型设备，清楚记录了他们在书房里的每次会面，以及剥夺我法律权利的计划。他们每多贪一天，案件里就多一页证据。",
        "## 第二章：最后的晚餐",
        "父亲生日宴当天，是他们准备把我扫地出门的日子。",
        "父亲站在妻子身旁，当着亲戚宣布：“我儿身体不便，以后家里的生意就交给儿媳打理。”",
        "亲戚们小声议论，等着看我被彻底踢出局。",
        "我转动轮椅，停在宴会厅巨大的投影屏幕前，当着所有人的面按下遥控器。",
        "“既然要谈家产，不如先看看这位贤惠儿媳和好父亲，准备怎么瓜分本该属于我的遗产。”",
        "屏幕亮起，画面里是他们在书房里的秘密会面，还有伪造医疗评估、修改公司决议并把遗产转到海外账户的录音，以及母亲当年立下的遗嘱公证书。",
        "整个大厅鸦雀无声，只剩父亲的红酒杯摔在地上。",
        "## 第三章：门前的审判",
        "父亲冲过来想抢走遥控器，但调查人员在他靠近前便进入会场。妻子看见资产转移记录，以及写明家产仅由我继承的遗嘱，终于明白计划已经失败。",
        "“你居然一直在收集证据？”父亲叫喊着。可在完整记录和公证遗嘱面前，他没有任何法律辩解。",
        "我盯着他们说：“母亲活着时，你们不敢碰她的财产。她刚离开，你们就想拿走她留给我的一切。今天，这些资产将回到合法继承人手里。”",
        "调查人员把他们带走。争议资产被冻结并归还给我，两人将面对正式起诉。",
        "我独自滑着轮椅走出那栋烂房子。阳光照在身上，我第一次觉得呼吸如此顺畅。从今天起，这个家终于干净了。",
        "尊严不是靠谁给的。把那些想害你的人送上审判席，才能真正拿回来。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "a-fathers-final-dignity",
    fileNo: "A-005",
    title: { en: "A Father’s Final Dignity", zh: "亲爹最后的尊严" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "Layla begs doctors to save her father while her stepmother steals his company—until a secret trust clause turns the hospital corridor into a courtroom.",
      zh: "蕾拉在医院哀求医生救父，后妈却趁机侵吞公司；一条秘密信托条款让病房走廊变成审判现场。"
    },
    warning: {
      en: "Fiction. Contains medical coercion and attempted financial abuse.",
      zh: "虚构故事。包含医疗胁迫与财产侵害情节。"
    },
    tone: "teal",
    glyph: "FD",
    content: {
      en: [
        "## Chapter One: The Calculation at His Bedside",
        "“Doctor, please reconnect my father’s ventilator. I will find the money today—I promise.”",
        "Beside a cold bench in the ICU corridor, Layla asked the physician to review the case. Before he could answer, her stepmother handed him a voluntary withdrawal-of-treatment form.",
        "“Stop pretending to be a devoted daughter,” said her stepmother, Anna, wrapped in expensive fur. “I am his legal spouse. I signed the order to stop treatment two hours ago.”",
        "Layla stared at the trembling fingerprint on the form. “He could still speak yesterday. He wanted to live. You stopped paying so your lover could take control of his company.”",
        "The tall man behind Anna—both a major shareholder and her secret partner—took the medical checks Layla had gathered and pushed them aside.",
        "“Anna and I control the company now. His shares and the trust your grandfather left you were reorganized five minutes ago. You cannot afford a legal fight, so how do you plan to stop us?”",
        "Directors and relatives lined the corridor, looking down at their phones and pretending not to witness the theft. Anna took her partner’s arm. “The decision is final. We are leaving.”",
        "Layla stood, wiped away her tears and removed an encrypted drive from her bag. It played a recording of Anna and her lover plotting to replace the will and end her father’s treatment. In her other hand was an official order opening an international money-laundering investigation.",
        "“Anna, you forgot the trust’s absolute protection clause. If the original beneficiary is subjected to an abnormal withdrawal of medical care, the trust automatically becomes a litigation fund and liquidates every asset held by the people responsible.”",
        "## Chapter Two: The Secret Clause",
        "The corridor fell silent except for the recorded voices. At the phrase ‘international money-laundering investigation,’ the lover’s face darkened. His cigar cutter hit the floor and his hands began to shake.",
        "“How did you get that recording? The trustees told us the fund was frozen.”",
        "Anna reached for the drive. “Do not listen to her. The company belongs to us.”",
        "Her partner stepped away from her. “That trust was designed to expose this exact scheme. Once the abnormal-withdrawal clause is triggered, it calls back every bridge loan made to the company and sends all evidence of our asset transfers directly to the tax authority.”",
        "Layla watched their alliance collapse, then pressed Send All on her phone.",
        "## Chapter Three: Total Liquidation",
        "Within seconds, every director’s phone filled with notices from banks and the commercial court. Because the controlling parties were suspected of criminal money laundering, company accounts had been frozen and liquidation had begun.",
        "The directors who had watched in silence surrounded Anna and her lover. Their own assets were now at risk, and their convenient loyalty vanished.",
        "Anna crawled toward Layla. “My daughter, I lost my mind. I will pay for your father’s care. I will call the best specialists. Please withdraw the investigation.”",
        "Her partner ran for the elevator. When the doors opened, federal tax investigators and police officers were already waiting to question him.",
        "Layla turned and entered the ICU. Under the new court order, her father was transferred to the city’s best medical team for protective care.",
        "Within half an hour, authorities restricted access to Anna’s disputed assets. The empire she had tried to seize was now subject to debt recovery and prosecution, all because of the records she had created herself.",
        "— End —"
      ],
      zh: [
        "## 第一章：病床前的算计",
        "“医生，我求求你，把我爸爸的呼吸机接回去！医药费我今天一定会凑齐！”",
        "在ICU长廊冰冷的长椅旁，蕾拉请求值班医生重新审查父亲的情况。医生还没说话，后妈便递来一份自愿放弃治疗同意书。",
        "“别演孝女了。我是你爸的法定配偶，两小时前已经签字停药。”后妈安娜穿着昂贵皮草，居高临下地看着她。",
        "蕾拉看着同意书上父亲颤抖变形的指印：“他昨天还能说话，明明想活下去。你为了让情人接管公司，故意断掉他的医药费！”",
        "后妈身后的男人既是公司大股东，也是她的秘密合伙人。他拿起蕾拉准备好的医疗费支票，随手推到一旁。",
        "“公司现在由我和安娜说了算。他的股份和你外公留下的信托，五分钟前已经完成重组。你承担不起一场诉讼，拿什么阻止我们？”",
        "几位董事和亲戚低头看手机，假装没看见这场掠夺。安娜挽着合伙人的手臂转身：“决定已经做完，我们走。”",
        "蕾拉站起来擦干眼泪，从背包拿出正在播放录音的加密U盘，以及税务总局的跨国洗钱调查令。录音里清楚传出后妈和情人偷换遗嘱、给父亲停药的密谋。",
        "“安娜，你忘了外公设立的信托有一条绝对保护条款。只要原始受益人遭遇非正常医疗放弃，信托就会自动变成诉讼基金，全面清盘责任人名下的资产。”",
        "## 第二章：秘密条款的威力",
        "长廊瞬间安静，只剩录音里贪婪的对话。情人听到跨国洗钱调查令，脸色铁青，手里的雪茄剪掉在地上。",
        "“你怎么会有录音？信托的绝对保护条款……那群老家伙不是说资金早就冻结了吗？”",
        "安娜试图抢夺U盘：“别听她吓唬人！公司是我们的！”",
        "合伙人立刻与安娜拉开距离：“那个信托就是为了揭露这种计划。一旦触发条款，信托会收回所有过桥资金，把资产转移证据送给税务局。”",
        "蕾拉看着他们的联盟瞬间瓦解，按下手机的群发键。",
        "## 第三章：绝对清盘",
        "几秒内，董事和亲戚的手机疯狂闪烁。商业法庭和银行通知显示：公司核心控股方涉嫌刑事犯罪及恶意洗钱，全部流水账户被冻结，进入破产清算。",
        "原本冷眼旁观的董事利益受损，瞬间将安娜和情人围在中间。",
        "安娜爬向蕾拉：“亲闺女，我鬼迷心窍！我出你爸爸的医药费，马上联系最好的专家，求你撤回调查令！”",
        "合伙人急忙走向电梯。电梯门一开，联邦税务稽查员和警察已经等在那里，要求他配合调查。",
        "蕾拉推开ICU大门。在司法介入下，父亲被紧急转入全市最好的医疗团队接受保护性救治。",
        "半小时后，后妈和合伙人的争议资产被依法限制处置。他们试图侵吞的公司进入债务追偿和司法程序，而所有后果都来自他们亲手留下的记录。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-last-watchman",
    fileNo: "A-002",
    title: { en: "The Last Watchman", zh: "最后的守夜人" },
    category: { en: "Justice & Reckoning", zh: "正义审判" },
    summary: {
      en: "A confused old man in a wheelchair is harassed for entertainment, but the medal in his hand carries the weight of a lifetime of public service.",
      zh: "一位坐在轮椅上的失智老人遭到街头骚扰，而他手中的勋章承载着一生的公共贡献。"
    },
    warning: {
      en: "Fiction. Contains harassment and mistreatment of an older adult.",
      zh: "虚构故事。包含对老年人的骚扰与不当对待。"
    },
    tone: "blue",
    glyph: "LW",
    content: {
      en: [
        "## Chapter One: A Cruel Performance",
        "No one would have guessed that the retired scientist sitting quietly in a wheelchair had once helped design one of the nation’s most important defense systems.",
        "I watched a group of young men laugh as they blocked my path and filmed me. My wife was gone, and my only son had died while serving on a national project. On this unfamiliar street, no one knew who I was.",
        "They moved my wheelchair away from the sidewalk, hid my lunch and mocked my confusion for a livestream. My coat was pulled open, but my hand never released the National Service Medal I carried as a reminder of an earlier life.",
        "They uploaded the performance for clicks, treating my distress as entertainment.",
        "They could not understand that the older man they dismissed had once spoken codes capable of placing the nation’s strategic shield on alert. Now I was trapped inside a confused body, trying to hold on to the memory of that life.",
        "## Chapter Two: The Price of Crossing the Line",
        "On Tuesday afternoon, their leader took my last hamburger and ordered the others to remove the old coat that still carried a classified identification plate.",
        "A new neighbor, Mrs. Mary, saw everything. She called the police. “Please, some young men are harassing an older man. He seems confused and needs help. You have to come now.”",
        "The first officers treated the incident as routine. Then an experienced sergeant pulled open my torn coat and saw the code engraved on the identity plate. One search of that number could place the entire federal security service on its highest alert.",
        "## Chapter Three: The Reckoning",
        "The sergeant’s face went white. He could barely speak as he called his superiors.",
        "Less than ten minutes later, several official vehicles arrived and the officers secured the block.",
        "The young men were still showing off their recordings when officers separated them from me. Then they watched a senior official stand before the dazed old man in the wheelchair and deliver a formal salute.",
        "The commanding officer knelt beside me, straightened my collar and faced the group. “The man you humiliated devoted his life to public service. The freedom you enjoy depends on people whose names you may never know.”",
        "## Chapter Four: The Last Dignity",
        "The group was taken away for questioning, and the case was referred to the appropriate court. Their future would be decided through due process.",
        "I was quietly returned to a secure medical center. Still lost inside fragments of memory, I pointed at the stars and told a guard, “We must calculate the angle correctly, or the Mars rover will miss its landing.”",
        "Behind me, the general straightened his back and saluted once more.",
        "Some lights do not fade with time. Those who stamp on the final ember may discover that the darkness remembers exactly who they are.",
        "— End —"
      ],
      zh: [
        "## 第一章：残酷的表演",
        "谁能想到，安静坐在轮椅上的退休科学家，曾参与设计国家重要的防御系统。",
        "我看着几个年轻人挡住去路，举着手机取笑我。老伴已经离开，唯一的儿子也在国家项目中因公去世。在这条陌生街道上，没人知道我是谁。",
        "他们把我的轮椅推离人行道，藏起午餐，还把我的困惑当作直播笑料。外套被拉开时，我仍紧握着那枚国家服务勋章，努力记住自己曾经的人生。",
        "他们把这场表演发到社交媒体上博取点击，把一个老人的不安当成娱乐。",
        "他们不会理解，被轻视的老人曾用一个代号让国家战略防线进入戒备。如今我被困在混乱的记忆里，只想守住过去留下的一点尊严。",
        "## 第二章：越界的代价",
        "周二下午，领头的年轻人拿走我仅剩的汉堡，又招呼同伴取下那件缝着绝密铭牌的旧外套。",
        "新搬来的邻居玛丽太太看见了一切。她拨通报警电话：“那几个年轻人在骚扰一位老人。他看起来有些困惑，需要帮助。请你们马上过来。”",
        "警察起初没有当回事，直到一名经验丰富的警长扯开旧外套，看见内侧刻着高密级代号的身份铭牌。那个编码一经查询，足以让整个联邦调查系统进入最高戒备。",
        "## 第三章：迟来的制止",
        "警长脸色惨白，立刻向上级紧急汇报。",
        "不到十分钟，几辆公务车辆赶到，执法人员迅速控制现场。",
        "几个年轻人还在展示偷拍视频，就被警员与我分开。他们看着一位只在新闻里出现过的高级官员走到轮椅前，郑重敬礼。",
        "带队官员蹲在我身旁，替我理好衣领，再对年轻人说：“这位老人把一生献给了公共事业。你们享受的自由，来自许多从未留下姓名的人。”",
        "## 第四章：最后的尊严",
        "几名年轻人被带走接受调查，案件将依法交给法院处理。",
        "我被秘密接回军事禁区内的特级疗养院，依旧糊涂地指着窗外星空对守卫说：“角度要算准，不然火星车落不下去。”",
        "将军站在我身后，再次挺直脊梁向我敬礼。",
        "世上总有一些光，不会因岁月流逝而暗淡。尊重他人，也是在守护我们共同生活的世界。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-logic-of-a-beast-in-the-mire",
    fileNo: "A-006",
    title: { en: "The Reckoning at Carter Estate", zh: "庄园里的审判" },
    category: { en: "Corporate Justice", zh: "职场正义" },
    summary: {
      en: "A powerful tycoon publicly humiliates Marcus, unaware that the quiet guest is the investigator who has spent three years documenting his illegal empire.",
      zh: "一名强势富豪当众羞辱马库斯，却不知道这位安静的来宾正是调查其非法商业帝国三年的调查官。"
    },
    warning: {
      en: "Fiction. Contains workplace discrimination, coercion and financial crime.",
      zh: "虚构故事。包含职场歧视、胁迫与金融犯罪情节。"
    },
    tone: "ink",
    glyph: "MJ",
    content: {
      en: [
        "“Who allowed an ordinary contractor into my private reception?” Carter demanded as every guest turned toward Marcus.",
        "To Carter, humiliation was another way to display power. He ordered security to remove Marcus’s invitation and made him stand alone beside the champagne table while the guests watched.",
        "Carter waved a check. “Sign a statement saying the audit found nothing, and I may let your consulting company work in this city again. Refuse, and I will make sure no client hires you.”",
        "He started a livestream, certain that public pressure would force Marcus to surrender. Instead, each threat became another piece of evidence.",
        "Marcus calmly touched the alert button inside his pocket. His tablet lit up, revealing authorized copies of the estate’s surveillance records and the company’s hidden financial accounts.",
        "Carter did not notice that the ballroom screens had changed. Then his recorded orders to exclude qualified employees and hide payments from auditors appeared before every guest.",
        "## Chapter Two: The Investigators Arrive",
        "The ballroom doors opened and a team from the Federal Special Audit Bureau entered with a court order.",
        "“This reception is now part of an active financial investigation,” the lead agent announced. The party’s illusion of luxury disappeared in an instant.",
        "Carter demanded to file a complaint. The commanding officer showed him the warrant, then turned to Marcus. “Sir, the three-year investigation into Carter Group’s discriminatory hiring program and international money laundering is complete. The Department of Justice is securing the relevant assets.”",
        "A thick case file was placed on the table. Page after page documented discriminatory directives, hidden accounts and fraudulent transfers.",
        "Marcus stood and displayed his senior investigator’s badge beneath the ballroom lights.",
        "“You asked what gave me the right to enter,” Marcus said. “I came to document how an empire built on intimidation responds when confronted with evidence.”",
        "## Chapter Three: An Empire Falls",
        "Every executive’s phone vibrated at once. Banks and regulators had restricted the disputed accounts pending review.",
        "Carter Group’s overseas credit, listed-company guarantees and personal transfers were placed under investigation. In one moment, the tycoon became a defendant required to answer for years of decisions.",
        "Guests who had flattered him turned away, desperate to prove that they had not participated. Federal officers separated the crowd and took Carter into custody as the party disintegrated around him.",
        "Marcus stopped beside the official vehicle. “You built your power by deciding who deserved an opportunity. The law will measure you by your actions.”",
        "The estate’s business records were secured as the investigators departed. Carter’s future would now be determined in court, not in a ballroom shaped by his influence.",
        "Dignity does not depend on wealth or status. It belongs to people who refuse to let intimidation define their place in the world.",
        "— End —"
      ],
      zh: [
        "“谁允许一个普通承包商进入我的私人酒会？”卡特厉声质问，所有宾客都转头看向马库斯。",
        "在卡特眼里，公开羞辱只是展示权力的另一种方式。他命令保安收走马库斯的邀请函，让他独自站在香槟桌旁接受围观。",
        "卡特挥着支票说：“签一份审计没有发现问题的声明，我或许还能让你的咨询公司继续在这座城市营业。拒绝的话，我会让所有客户都远离你。”",
        "他打开直播，确信舆论压力会迫使马库斯妥协。可他的每一句威胁，都成了新的证据。",
        "马库斯平静地按下口袋里的警报按钮。平板电脑亮起，显示出依法取得的庄园监控记录和公司隐藏账户。",
        "卡特没有发现宴会厅屏幕已经切换。随后，他排斥合格员工、向审计人员隐瞒付款的录音出现在所有宾客面前。",
        "## 第二章：审判者降临",
        "宴会厅大门打开，联邦特别审计局的调查团队带着法院授权文件进入。",
        "“这场酒会现在属于金融调查的一部分。”带队人员宣布。酒会营造出的奢华幻象瞬间消失。",
        "卡特还在叫嚷投诉，负责人先向他出示授权文件，再转向马库斯：“长官，针对卡特集团长达三年的歧视性招聘计划及跨国洗钱调查已经完成，司法部门正在保护相关资产。”",
        "厚厚的卷宗被放在桌上，每一页都是歧视性指令、隐藏账户和欺诈转账记录。",
        "马库斯缓缓站起，在宴会厅灯光下出示高级调查官证件。",
        "“你问我凭什么进来？”马库斯说，“我来记录一个依靠恐吓建立的商业帝国，在证据面前会作出什么反应。”",
        "## 第三章：帝国崩塌",
        "庄园内所有高管的手机同时震动，银行和监管部门已经依法限制争议账户。",
        "卡特集团的海外信贷、上市担保和个人转账进入调查。他从富豪变成必须为多年决策作出解释的被告。",
        "刚才还点头哈腰的权贵为了证明清白，纷纷与他切割。特勤人员隔开人群，在混乱中将卡特依法拘捕。",
        "马库斯在公务车辆旁停下：“你曾经决定谁配得到机会，现在法律会按照你的行为来衡量你。”",
        "调查人员保护好庄园里的商业记录后离开。卡特的未来将由法庭决定，不再由他的个人影响力决定。",
        "尊严从来不依赖财富或地位。它属于每一个拒绝让恐吓定义自己位置的人。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-viper-in-the-nest",
    fileNo: "A-007",
    title: { en: "The Viper in the Nest", zh: "温床上的毒蛇" },
    category: { en: "Family Betrayal", zh: "家庭背叛" },
    summary: {
      en: "A pregnant woman watches her husband and sister build a secret life inside her home, quietly saving every message until the day they demand her property.",
      zh: "一名孕妇看着丈夫和妹妹在自己家里构筑秘密关系，默默保存证据，等待他们逼她交出财产的那一天。"
    },
    warning: {
      en: "Fiction. Contains infidelity, coercion and financial abuse.",
      zh: "虚构故事。包含婚内背叛、胁迫与财产侵害情节。"
    },
    tone: "green",
    glyph: "VN",
    content: {
      en: [
        "## Chapter One: The Viper in the Nest",
        "Pregnancy made me sleep deeply. Every night after I drifted off, the man beside me rose quietly, crossed the hallway and opened my sister’s bedroom door.",
        "They believed their arrangement was invisible. At dinner, my sister peeled shrimp for me; in the bathroom, she showed my husband the curve of her own pregnant belly. Together they built a net inside my family. He moved assets while she prepared to take control after giving birth. Their final plan was to label me with postpartum depression, send me to a facility and throw me out of my own home.",
        "They treated me as a tool in their betrayal and repeatedly brought me bowls of what they called nourishing soup.",
        "I never drank it. I watched their performance and their dream of wealth with quiet amusement. A hidden camera had already been installed inside my wardrobe, and every private conversation was synchronized to my cloud archive.",
        "They called it love. I saw two mice dancing their final waltz on the road to a trap.",
        "## Chapter Two: The Final Threat",
        "My due date arrived, and they chose it as the day to confront me.",
        "My sister entered the bedroom in a carefully chosen maternity dress. My husband followed, and the gentleness he used to wear had disappeared from his face.",
        "“Stop pretending,” he said. “Sign over the property and the shares. If you resist, we will use the edited medical report to challenge your custody rights and remove you from this house.”",
        "My sister looked away. “Do not blame us. You had the chance to give up your place quietly.”",
        "I sat at the edge of the bed and smiled. Outside the window, dozens of black enforcement vehicles had already sealed the estate.",
        "“Everything you want is here.” I placed a stack of documents on the bed.",
        "They reached for it, expecting an inventory of property. The first page showed records of illegal fundraising, forged transfers and a signed complaint documenting long-term coercion.",
        "The front doors opened and investigators entered with a court order.",
        "## Chapter Three: Evidence and Judgment",
        "A special enforcement team secured the villa. Faced with the officers and the recordings, my sister stopped pretending that nothing had happened.",
        "My husband immediately pointed at her. “It was all her idea. She planned everything. I am a victim too.”",
        "To save himself, he pushed every decision onto the woman he claimed to love. Their alliance collapsed as soon as the evidence appeared. The law would decide the rest.",
        "“Mr. Lin and Ms. Su, you are under investigation on suspicion of commercial fraud, forged documents and conspiracy to commit unlawful confinement.”",
        "They were taken away for questioning. My sister and husband both continued to deny responsibility, but the recordings and financial records spoke for themselves.",
        "Their accounts were sealed and their supposed love entered the record as evidence. I would carry my own child forward and cut the last thread tying me to their betrayal.",
        "As officers led them to the vehicles, I offered one final sentence. “You wanted this house. A court will now decide what belongs to whom.”",
        "Dignity is not proved by birth or status. It is reclaimed when cruelty no longer controls the door to your own home.",
        "— End —"
      ],
      zh: [
        "## 第一章：温床上的毒蛇",
        "我睡得很沉，因为这是怀孕后的常态。每晚在我睡着后，枕边的男人都会轻手轻脚起身，穿过走廊，推开妹妹房间的门。",
        "他们以为这场地下交易天衣无缝。餐桌上，妹妹会贴心地为我剥虾，转头却在洗手间向我丈夫炫耀她已经显怀的肚子。他们在我的家庭里编织捕网：丈夫转移资产，妹妹准备在生产后夺取家庭主权，最后再以产后抑郁为由将我送进疗养院。",
        "他们把我当成这场伦理悲剧里的工具人，还时不时让我喝下所谓的补汤。",
        "但我从不喝。我看着他们自导自演，只觉得好笑。卧室衣柜里早已装好高清针孔摄像头，所有亲密聊天记录也同步上传到我的云端备份。",
        "他们以为这是爱情，其实只是两只老鼠在通往捕鼠夹的路上跳最后一场华尔兹。",
        "## 第二章：最后的胁迫",
        "预产期到了，这是他们决定摊牌的日子。",
        "妹妹穿着精心挑选的孕妇裙走进卧室，丈夫跟在身后，原本温和的语气已经变得冷漠。",
        "“别装了。”丈夫说，“把房产证和股权转让书签了。你要是拒绝，我们就用剪辑过的医疗报告争夺监护权，再把你赶出这套房子。”",
        "妹妹移开视线：“姐姐，别怪我们。你原本可以安静地让出位置。”",
        "我坐在床边平静地笑了笑，望向窗外——几十辆司法执行局的黑色轿车已经封锁整个庄园。",
        "“你们想要的，都在这里。”我把一叠资料扔在床上。",
        "他们以为那是财产清单，急忙翻开。第一页却是非法集资记录、伪造的转让文件，以及证明他们长期胁迫我的实名举报信。",
        "别墅大门打开，调查人员带着法院授权文件进入。",
        "## 第三章：证据与审判",
        "执行人员控制现场。面对警员和完整录音，妹妹终于无法继续假装什么都没有发生。",
        "丈夫立刻指着她说：“全是她的主意，是她策划了一切。我也是受害者！”",
        "为了保护自己，他把所有决定都推给曾经口口声声说爱的人。他们的联盟在证据出现后立刻瓦解，其余问题将交给法律判断。",
        "“林先生、苏小姐，你们涉嫌商业诈骗、伪造文件及共谋非法限制人身自由，请配合调查。”",
        "两人被带走接受询问。他们仍在互相推卸责任，但录音和财务记录已经说明了一切。",
        "他们的争议资金被依法限制，所谓爱情成了法庭证据。我会带着自己的孩子，彻底告别这段充满欺骗的过去。",
        "被带上公务车辆前，我最后对他们说：“你们想要这套房子，现在就让法院决定它属于谁。”",
        "尊严不需要靠出身证明。它来自把欺凌者挡在自己人生门外的勇气。",
        "—— 全文完 ——"
      ]
    }
  },
  {
    slug: "the-tattered-toy-in-the-rain",
    fileNo: "A-008",
    title: { en: "The Tattered Toy in the Rain", zh: "雨夜里的破烂玩偶" },
    category: { en: "Lost & Found", zh: "失而复得" },
    summary: {
      en: "A ten-year-old girl shelters outside the restaurant where someone else is celebrating her birthday, until a geotagged post leads the family searching for her straight to the door.",
      zh: "十岁女孩躲在一家餐厅外避雨，窗内却有人冒用她的生日庆祝；一条带定位的动态，让寻找她多日的家人终于来到门前。"
    },
    warning: {
      en: "Fiction. Contains child abandonment, bullying and family loss.",
      zh: "虚构故事。包含儿童被遗弃、欺凌与亲人离世情节。"
    },
    tone: "cream",
    glyph: "RT",
    content: {
      en: [
        "## Chapter One: A Birthday Taken Away",
        "Today was my tenth birthday, and the third day since my stepmother, Mary, had sent me away from home.",
        "Cold rain slipped through the holes in my plastic shoes. I held a worn teddy bear against my chest—the only keepsake my mother had left me.",
        "My father had died after a long illness one month earlier. Mary quickly took control of the house and showed me a document I could not understand, saying that he had left everything to her.",
        "Three days ago, she received a telephone call and told the person on the other end that I had already left with relatives. That evening, she packed my clothes into a bag and ordered me out into the rain.",
        "Before he became ill, Father had reserved a table at a restaurant in the city center for my tenth birthday. After days without a proper meal, I followed the route from memory, hoping the kitchen might have something left over.",
        "Through the tall windows, I saw a brightly lit party. Amy was also ten, although her birthday was still a month away. Mary had replaced my name on the cake and presented the celebration as Amy’s.",
        "Amy came outside carrying a plate of leftover cake. Instead of offering it to me, she set it beside the rubbish bin and used her phone to record me reaching for it.",
        "She uploaded the video to social media and added the restaurant’s location, expecting her friends to laugh at the child sheltering beneath the trees.",
        "Mary followed her outside, noticed the teddy bear in my arms and took it away. She threw it toward the storm drain, dismissing it as something that belonged in the past.",
        "I hurried after the bear, slipped in the mud and watched the rain carry it out of reach.",
        "## Chapter Two: The Cars in the Rain",
        "Several black cars arrived outside the restaurant. A security team protected the area, contacted the restaurant manager and asked that all camera recordings be preserved until the police arrived.",
        "A large umbrella appeared above me. An older man with silver hair hurried forward while a medical worker wrapped me in a thermal blanket and checked my breathing.",
        "Mary demanded that everyone leave, insisting that she did not know me and that I had no connection to the family.",
        "A lawyer opened a black folder and showed her an emergency protection order. The older man was the chairman of Howard Financial Group—and my maternal grandfather.",
        "Years earlier, my mother had left the Howard family to build a private life with my father. She had kept my identity out of public records, and Mary had assumed that no relatives would ever come looking for me.",
        "The lawyer explained that a family trust had been created when my mother was born. It remained sealed after she left, but its identity review was scheduled to begin shortly before my tenth birthday.",
        "Three days earlier, the trustees had insisted on meeting me in person. Mary became frightened, sent me away and falsely claimed that relatives had collected me.",
        "The trust named me as its sole beneficiary. Until I reached adulthood, independent trustees—not any member of the household—would continue to manage and protect the assets.",
        "The lawyer also explained that the disputed will, the missing-child report and the decision to remove me from the house would now be examined by the proper authorities.",
        "The team had searched for three days. Amy’s public post, complete with the restaurant location, finally gave them the lead they needed.",
        "## Chapter Three: The Name Inside the Crown",
        "My grandfather asked the staff to recover the teddy bear. A few minutes later, it returned inside a clear evidence bag, soaked but still intact.",
        "Hidden in its back seam was a small encrypted key bearing the Howard family emblem. The key opened a protected archive that my mother had prepared years earlier.",
        "A screen displayed her recorded message. ‘Father, if you are watching this, my daughter has reached her tenth birthday and I could not be beside her. Please find her. Give back not only her inheritance, but also her name, her birthday and the chance to choose her own life.’",
        "Mary finally understood that the document she had relied upon could not override the protected trust or the evidence now being reviewed.",
        "The lawyer then presented the purchase record for the crystal crown used at the party. Its inscription carried my initials because Father had ordered it as my birthday gift.",
        "My grandfather looked at the location tag still visible on Amy’s phone. ‘You intended this post to embarrass a child,’ he said. ‘Instead, it helped establish where she was and when she was found.’",
        "Police officers arrived, reviewed the protection order and restaurant footage, and asked Mary to accompany them for questioning.",
        "A child-welfare specialist stayed with Amy and arranged temporary care while the adults’ actions were investigated.",
        "The medical team took me to the hospital. My grandfather kept hold of my hand, and the cars followed quietly through the rain.",
        "## Epilogue",
        "After a full investigation, a court found Mary responsible for forged financial documents, fraud, abandonment and mistreatment of a child. Amy entered family care and received counseling for the behavior recorded that night.",
        "The court and trustees confirmed my status as the trust’s sole beneficiary. The assets would remain under independent management until I became an adult.",
        "My grandfather never asked me to forget the past. He arranged medical care, counseling and a quiet room where I could decide when I was ready to talk.",
        "Months later, I held the cleaned and repaired teddy bear beside a bright window. The rain had not erased my name. It had carried the final clue to the people who were looking for me.",
        "— End —"
      ],
      zh: [
        "## 第一章：被拿走的生日",
        "今天是我十岁生日，也是继母玛丽让我离开家的第三天。",
        "冰冷雨水从塑料鞋的破洞里灌进来。我紧紧抱着一只旧毛绒熊——那是亲生母亲留给我的唯一纪念。",
        "一个月前，父亲因长期重病去世。玛丽很快控制了房子，又拿出一份我看不懂的文件，声称父亲已经把一切都留给她。",
        "三天前，她接到一通电话，对电话里的人说我已经被亲戚接走。当天晚上，她把我的衣服装进袋子，让我离开了家。",
        "父亲生病前，曾在市中心一家餐厅预订我的十岁生日宴。几天没有好好吃饭后，我沿着记忆中的路线找来，只希望厨房还有一点剩下的食物。",
        "隔着落地窗，我看见里面灯火明亮。艾米也只有十岁，但她真正的生日还在一个月以后。玛丽换掉了蛋糕上的名字，把这场庆祝说成属于艾米。",
        "艾米端着剩下的蛋糕走出来。她没有把食物递给我，而是放在垃圾桶旁，用手机拍下我伸手去拿的样子。",
        "她把视频发到社交媒体，还加上餐厅定位，以为朋友们会取笑躲在树下避雨的孩子。",
        "玛丽随后走出来，看见我怀里的毛绒熊，便把它拿走，扔向路旁的排水口，说这种旧东西早该被丢掉。",
        "我急忙追过去，却在泥水中滑倒，只能看着雨水把毛绒熊带到够不到的地方。",
        "## 第二章：雨中的车队",
        "几辆黑色轿车停在餐厅外。安保人员保护现场、联系餐厅负责人，并要求保存全部监控，等待警方到场。",
        "一把大伞挡住了头顶的雨。头发花白的老人快步走到我面前，随行医护人员用保温毯裹住我，检查我的呼吸和体温。",
        "玛丽要求所有人离开，坚持说她不认识我，也否认我与这个家庭有任何关系。",
        "律师打开黑色文件夹，向她出示法院签发的紧急保护令。老人是霍华德金融集团董事局主席，也是我的亲外公。",
        "多年前，母亲离开霍华德家族，与父亲过上了低调生活。她没有公开我的身份，玛丽因此认定不会再有亲人来寻找我。",
        "律师解释，霍华德家族在母亲出生时设立了一份家族信托。母亲离开后，信托一直封存，但身份核验会在我十岁生日之前自动启动。",
        "三天前，受托机构坚持必须与我本人见面。玛丽慌了，把我送走，又谎称亲戚已经把我接走。",
        "信托文件写明我是唯一受益人。在我成年以前，全部资产都由独立受托机构管理和保护，任何家庭成员都不能私自处置。",
        "律师还说明，存在争议的遗嘱、儿童失踪记录，以及把我赶出住所的行为，都将交由有关部门依法调查。",
        "寻找我的团队已经奔波三天。艾米公开发布的动态带有餐厅定位，终于提供了最关键的线索。",
        "## 第三章：皇冠里的名字",
        "外公请工作人员找回毛绒熊。几分钟后，它被装在透明证物袋里送回来，虽然湿透，却依然完整。",
        "毛绒熊背面的夹层藏着一枚刻有霍华德家徽的加密钥匙。它打开了母亲多年前留下的一份受保护档案。",
        "屏幕上出现母亲的录像：‘父亲，如果你看到这段话，我的女儿已经十岁，而我没能陪在她身边。请找到她。不要只把继承权还给她，也请把她的名字、生日和选择人生的机会一起还给她。’",
        "玛丽终于明白，她依赖的那份文件无法推翻受保护的信托，也无法改变正在接受审查的证据。",
        "律师随后拿出宴会上那顶水晶皇冠的购买记录。皇冠内侧刻着我的姓名首字母，因为那原本是父亲为我订制的生日礼物。",
        "外公看着艾米手机上仍然显示的定位：‘你原本想用这条动态让一个孩子难堪，它却帮助我们确认了她在哪里，以及被找到的时间。’",
        "警员到场后核对保护令和餐厅监控，并请玛丽一同前往接受调查。",
        "儿童福利工作人员留在艾米身边，在调查成年人行为期间为她安排临时照护。",
        "医护人员把我送往医院。外公始终握着我的手，车队安静地跟在救护车后，穿过雨夜。",
        "## 尾声",
        "完整调查结束后，法院认定玛丽需要为伪造金融文件、欺诈、遗弃及不当对待儿童承担责任。艾米由亲属照护，并接受针对当晚行为的心理辅导。",
        "法院与受托机构确认我是家族信托的唯一受益人。在我成年以前，全部资产继续由独立机构管理。",
        "外公没有要求我立刻忘记过去。他为我安排医疗照护和心理咨询，也给了我一个安静的房间，等我愿意主动开口。",
        "几个月后，我抱着清洗、缝补好的毛绒熊坐在明亮的窗边。那场雨没有冲走我的名字，反而把最后一条线索送到了寻找我的人手里。",
        "—— 全文完 ——"
      ]
    }
  }
];
